// === COUNTRY ===
// Morgan Wallen
{ title: "Whiskey Glasses", artist: "Morgan Wallen" },
{ title: "Last Night", artist: "Morgan Wallen" },
{ title: "Thought You Should Know", artist: "Morgan Wallen" },
{ title: "Wasted on You", artist: "Morgan Wallen" },
{ title: "Cover Me Up", artist: "Morgan Wallen" },
{ title: "You Proof", artist: "Morgan Wallen" },
{ title: "Sand in My Boots", artist: "Morgan Wallen" },
{ title: "More Than My Hometown", artist: "Morgan Wallen" },
{ title: "Chasin You", artist: "Morgan Wallen" },
{ title: "7 Summers", artist: "Morgan Wallen" },
{ title: "Spin You Around", artist: "Morgan Wallen" },
{ title: "Flower Shops", artist: "Morgan Wallen" },
{ title: "One Thing at a Time", artist: "Morgan Wallen" },
{ title: "Everything I Love", artist: "Morgan Wallen" },
{ title: "Thinkin Bout Me", artist: "Morgan Wallen" },
// Luke Combs
{ title: "Fast Car", artist: "Luke Combs" },
{ title: "Beautiful Crazy", artist: "Luke Combs" },
{ title: "When It Rains It Pours", artist: "Luke Combs" },
{ title: "Hurricane", artist: "Luke Combs" },
{ title: "Beer Never Broke My Heart", artist: "Luke Combs" },
{ title: "She Got the Best of Me", artist: "Luke Combs" },
{ title: "Even Though I'm Leaving", artist: "Luke Combs" },
{ title: "Better Together", artist: "Luke Combs" },
{ title: "Lovin on You", artist: "Luke Combs" },
{ title: "One Number Away", artist: "Luke Combs" },
{ title: "Forever After All", artist: "Luke Combs" },
{ title: "Doin This", artist: "Luke Combs" },
{ title: "The Kind of Love We Make", artist: "Luke Combs" },
{ title: "Where the Wild Things Are", artist: "Luke Combs" },
{ title: "Ain't Far From It", artist: "Luke Combs" },
// Zach Bryan
{ title: "Something in the Orange", artist: "Zach Bryan" },
{ title: "Heading South", artist: "Zach Bryan" },
{ title: "I Remember Everything", artist: "Zach Bryan" },
{ title: "Sun to Me", artist: "Zach Bryan" },
{ title: "Burn Burn Burn", artist: "Zach Bryan" },
{ title: "Oklahoma Smokeshow", artist: "Zach Bryan" },
{ title: "Revival", artist: "Zach Bryan" },
{ title: "Hey Driver", artist: "Zach Bryan" },
{ title: "Tourniquet", artist: "Zach Bryan" },
{ title: "Open the Gate", artist: "Zach Bryan" },
{ title: "Condemned", artist: "Zach Bryan" },
{ title: "Pink Skies", artist: "Zach Bryan" },
{ title: "28", artist: "Zach Bryan" },
{ title: "Nine Ball", artist: "Zach Bryan" },
{ title: "Boys of Faith", artist: "Zach Bryan" },
// Chris Stapleton
{ title: "Tennessee Whiskey", artist: "Chris Stapleton" },
{ title: "Broken Halos", artist: "Chris Stapleton" },
{ title: "Starting Over", artist: "Chris Stapleton" },
{ title: "White Horse", artist: "Chris Stapleton" },
{ title: "Parachute", artist: "Chris Stapleton" },
{ title: "Fire Away", artist: "Chris Stapleton" },
{ title: "Millionaire", artist: "Chris Stapleton" },
{ title: "Cold", artist: "Chris Stapleton" },
{ title: "Joy of My Life", artist: "Chris Stapleton" },
{ title: "You Should Probably Leave", artist: "Chris Stapleton" },
{ title: "Either Way", artist: "Chris Stapleton" },
{ title: "Traveller", artist: "Chris Stapleton" },
{ title: "Maggie's Song", artist: "Chris Stapleton" },
{ title: "What Are You Listening To", artist: "Chris Stapleton" },
{ title: "Think I'm in Love with You", artist: "Chris Stapleton" },
// Luke Bryan
{ title: "Drunk on You", artist: "Luke Bryan" },
{ title: "Country Girl", artist: "Luke Bryan" },
{ title: "Play It Again", artist: "Luke Bryan" },
{ title: "Rain Is a Good Thing", artist: "Luke Bryan" },
{ title: "That's My Kind of Night", artist: "Luke Bryan" },
{ title: "Crash My Party", artist: "Luke Bryan" },
{ title: "Strip It Down", artist: "Luke Bryan" },
{ title: "Kick the Dust Up", artist: "Luke Bryan" },
{ title: "Knockin Boots", artist: "Luke Bryan" },
{ title: "One Margarita", artist: "Luke Bryan" },
{ title: "Waves", artist: "Luke Bryan" },
{ title: "I Don't Want This Night to End", artist: "Luke Bryan" },
{ title: "Do I", artist: "Luke Bryan" },
{ title: "Huntin Fishin and Lovin Every Day", artist: "Luke Bryan" },
{ title: "Most People Are Good", artist: "Luke Bryan" },
// Jason Aldean
{ title: "Dirt Road Anthem", artist: "Jason Aldean" },
{ title: "Big Green Tractor", artist: "Jason Aldean" },
{ title: "She's Country", artist: "Jason Aldean" },
{ title: "Burnin It Down", artist: "Jason Aldean" },
{ title: "My Kinda Party", artist: "Jason Aldean" },
{ title: "You Make It Easy", artist: "Jason Aldean" },
{ title: "Fly Over States", artist: "Jason Aldean" },
{ title: "Night Train", artist: "Jason Aldean" },
{ title: "Hicktown", artist: "Jason Aldean" },
{ title: "Take a Little Ride", artist: "Jason Aldean" },
{ title: "Drowns the Whiskey", artist: "Jason Aldean" },
{ title: "Any Ol Barstool", artist: "Jason Aldean" },
{ title: "Tattoos on This Town", artist: "Jason Aldean" },
{ title: "Lights Come On", artist: "Jason Aldean" },
{ title: "Try That in a Small Town", artist: "Jason Aldean" },
// Thomas Rhett
{ title: "Die a Happy Man", artist: "Thomas Rhett" },
{ title: "Marry Me", artist: "Thomas Rhett" },
{ title: "Crash and Burn", artist: "Thomas Rhett" },
{ title: "Life Changes", artist: "Thomas Rhett" },
{ title: "It Goes Like This", artist: "Thomas Rhett" },
{ title: "T-Shirt", artist: "Thomas Rhett" },
{ title: "Star of the Show", artist: "Thomas Rhett" },
{ title: "Beer Can't Fix", artist: "Thomas Rhett" },
{ title: "Remember You Young", artist: "Thomas Rhett" },
{ title: "Look What God Gave Her", artist: "Thomas Rhett" },
{ title: "Make Me Wanna", artist: "Thomas Rhett" },
{ title: "Craving You", artist: "Thomas Rhett" },
{ title: "Country Again", artist: "Thomas Rhett" },
{ title: "Slow Down Summer", artist: "Thomas Rhett" },
{ title: "Get Me Some of That", artist: "Thomas Rhett" },
// Carrie Underwood
{ title: "Before He Cheats", artist: "Carrie Underwood" },
{ title: "Blown Away", artist: "Carrie Underwood" },
{ title: "Jesus Take the Wheel", artist: "Carrie Underwood" },
{ title: "Cowboy Casanova", artist: "Carrie Underwood" },
{ title: "Last Name", artist: "Carrie Underwood" },
{ title: "Undo It", artist: "Carrie Underwood" },
{ title: "Good Girl", artist: "Carrie Underwood" },
{ title: "Two Black Cadillacs", artist: "Carrie Underwood" },
{ title: "Something in the Water", artist: "Carrie Underwood" },
{ title: "Church Bells", artist: "Carrie Underwood" },
{ title: "Cry Pretty", artist: "Carrie Underwood" },
{ title: "The Champion", artist: "Carrie Underwood" },
{ title: "Smoke Break", artist: "Carrie Underwood" },
{ title: "Southbound", artist: "Carrie Underwood" },
{ title: "If I Didn't Love You", artist: "Carrie Underwood" },
// Miranda Lambert
{ title: "The House That Built Me", artist: "Miranda Lambert" },
{ title: "Gunpowder and Lead", artist: "Miranda Lambert" },
{ title: "Mama's Broken Heart", artist: "Miranda Lambert" },
{ title: "Somethin Bad", artist: "Miranda Lambert" },
{ title: "Over You", artist: "Miranda Lambert" },
{ title: "Bluebird", artist: "Miranda Lambert" },
{ title: "Vice", artist: "Miranda Lambert" },
{ title: "Tin Man", artist: "Miranda Lambert" },
{ title: "Automatic", artist: "Miranda Lambert" },
{ title: "White Liar", artist: "Miranda Lambert" },
{ title: "Kerosene", artist: "Miranda Lambert" },
{ title: "Heart Like Mine", artist: "Miranda Lambert" },
{ title: "If I Was a Cowboy", artist: "Miranda Lambert" },
{ title: "Settling Down", artist: "Miranda Lambert" },
{ title: "Drunk", artist: "Miranda Lambert" },
// Keith Urban
{ title: "Blue Ain't Your Color", artist: "Keith Urban" },
{ title: "Somebody Like You", artist: "Keith Urban" },
{ title: "Days Go By", artist: "Keith Urban" },
{ title: "You'll Think of Me", artist: "Keith Urban" },
{ title: "Making Memories of Us", artist: "Keith Urban" },
{ title: "Stupid Boy", artist: "Keith Urban" },
{ title: "Without You", artist: "Keith Urban" },
{ title: "Tonight I Wanna Cry", artist: "Keith Urban" },
{ title: "Long Hot Summer", artist: "Keith Urban" },
{ title: "Wasted Time", artist: "Keith Urban" },
{ title: "Cop Car", artist: "Keith Urban" },
{ title: "John Cougar John Deere John 3:16", artist: "Keith Urban" },
{ title: "The Fighter", artist: "Keith Urban" },
{ title: "Wild Hearts", artist: "Keith Urban" },
{ title: "Coming Home", artist: "Keith Urban" },
// Tim McGraw
{ title: "Humble and Kind", artist: "Tim McGraw" },
{ title: "Live Like You Were Dying", artist: "Tim McGraw" },
{ title: "Don't Take the Girl", artist: "Tim McGraw" },
{ title: "It's Your Love", artist: "Tim McGraw" },
{ title: "Something Like That", artist: "Tim McGraw" },
{ title: "I Like It I Love It", artist: "Tim McGraw" },
{ title: "Just to See You Smile", artist: "Tim McGraw" },
{ title: "Real Good Man", artist: "Tim McGraw" },
{ title: "Shotgun Rider", artist: "Tim McGraw" },
{ title: "Meanwhile Back at Mamas", artist: "Tim McGraw" },
{ title: "My Little Girl", artist: "Tim McGraw" },
{ title: "Felt Good on My Lips", artist: "Tim McGraw" },
{ title: "Highway Don't Care", artist: "Tim McGraw" },
{ title: "7500 OBO", artist: "Tim McGraw" },
{ title: "Standing Room Only", artist: "Tim McGraw" },
// Kenny Chesney
{ title: "No Shoes No Shirt No Problems", artist: "Kenny Chesney" },
{ title: "When the Sun Goes Down", artist: "Kenny Chesney" },
{ title: "She Thinks My Tractor's Sexy", artist: "Kenny Chesney" },
{ title: "There Goes My Life", artist: "Kenny Chesney" },
{ title: "Somewhere with You", artist: "Kenny Chesney" },
{ title: "You and Tequila", artist: "Kenny Chesney" },
{ title: "Pirate Flag", artist: "Kenny Chesney" },
{ title: "American Kids", artist: "Kenny Chesney" },
{ title: "Summertime", artist: "Kenny Chesney" },
{ title: "Living in Fast Forward", artist: "Kenny Chesney" },
{ title: "Anything but Mine", artist: "Kenny Chesney" },
{ title: "The Good Stuff", artist: "Kenny Chesney" },
{ title: "Young", artist: "Kenny Chesney" },
{ title: "How Forever Feels", artist: "Kenny Chesney" },
{ title: "Get Along", artist: "Kenny Chesney" },
// Blake Shelton
{ title: "God Gave Me You", artist: "Blake Shelton" },
{ title: "Austin", artist: "Blake Shelton" },
{ title: "Boys Round Here", artist: "Blake Shelton" },
{ title: "Honey Bee", artist: "Blake Shelton" },
{ title: "God's Country", artist: "Blake Shelton" },
{ title: "Sangria", artist: "Blake Shelton" },
{ title: "Mine Would Be You", artist: "Blake Shelton" },
{ title: "I'll Name the Dogs", artist: "Blake Shelton" },
{ title: "Neon Light", artist: "Blake Shelton" },
{ title: "Sure Be Cool If You Did", artist: "Blake Shelton" },
{ title: "Doin What She Likes", artist: "Blake Shelton" },
{ title: "Came Here to Forget", artist: "Blake Shelton" },
{ title: "Footloose", artist: "Blake Shelton" },
{ title: "Turnin Me On", artist: "Blake Shelton" },
{ title: "Nobody But You", artist: "Blake Shelton" },
// Dolly Parton
{ title: "Jolene", artist: "Dolly Parton" },
{ title: "9 to 5", artist: "Dolly Parton" },
{ title: "I Will Always Love You", artist: "Dolly Parton" },
{ title: "Coat of Many Colors", artist: "Dolly Parton" },
{ title: "Islands in the Stream", artist: "Dolly Parton" },
{ title: "Here You Come Again", artist: "Dolly Parton" },
{ title: "Two Doors Down", artist: "Dolly Parton" },
{ title: "Why'd You Come in Here Lookin Like That", artist: "Dolly Parton" },
{ title: "Tennessee Homesick Blues", artist: "Dolly Parton" },
{ title: "Rockin Years", artist: "Dolly Parton" },
{ title: "Light of a Clear Blue Morning", artist: "Dolly Parton" },
{ title: "Working Girl", artist: "Dolly Parton" },
{ title: "Those Memories of You", artist: "Dolly Parton" },
{ title: "But You Know I Love You", artist: "Dolly Parton" },
{ title: "Old Flames Can't Hold a Candle to You", artist: "Dolly Parton" },
// Johnny Cash
{ title: "Ring of Fire", artist: "Johnny Cash" },
{ title: "Folsom Prison Blues", artist: "Johnny Cash" },
{ title: "I Walk the Line", artist: "Johnny Cash" },
{ title: "Hurt", artist: "Johnny Cash" },
{ title: "Man in Black", artist: "Johnny Cash" },
{ title: "Jackson", artist: "Johnny Cash" },
{ title: "A Boy Named Sue", artist: "Johnny Cash" },
{ title: "Get Rhythm", artist: "Johnny Cash" },
{ title: "Sunday Mornin Comin Down", artist: "Johnny Cash" },
{ title: "Ghost Riders in the Sky", artist: "Johnny Cash" },
{ title: "God's Gonna Cut You Down", artist: "Johnny Cash" },
{ title: "Big River", artist: "Johnny Cash" },
{ title: "Cry Cry Cry", artist: "Johnny Cash" },
{ title: "Cocaine Blues", artist: "Johnny Cash" },
{ title: "Tennessee Flat Top Box", artist: "Johnny Cash" },
// Willie Nelson
{ title: "On the Road Again", artist: "Willie Nelson" },
{ title: "Blue Eyes Crying in the Rain", artist: "Willie Nelson" },
{ title: "Always on My Mind", artist: "Willie Nelson" },
{ title: "Whiskey River", artist: "Willie Nelson" },
{ title: "Mammas Don't Let Your Babies Grow Up to Be Cowboys", artist: "Willie Nelson" },
{ title: "Funny How Time Slips Away", artist: "Willie Nelson" },
{ title: "Georgia on My Mind", artist: "Willie Nelson" },
{ title: "Angel Flying Too Close to the Ground", artist: "Willie Nelson" },
{ title: "To All the Girls I've Loved Before", artist: "Willie Nelson" },
{ title: "Good Hearted Woman", artist: "Willie Nelson" },
{ title: "My Heroes Have Always Been Cowboys", artist: "Willie Nelson" },
{ title: "Pancho and Lefty", artist: "Willie Nelson" },
{ title: "City of New Orleans", artist: "Willie Nelson" },
{ title: "Forgiving You Was Easy", artist: "Willie Nelson" },
{ title: "Seven Spanish Angels", artist: "Willie Nelson" },
// George Strait
{ title: "Amarillo by Morning", artist: "George Strait" },
{ title: "Check Yes or No", artist: "George Strait" },
{ title: "The Chair", artist: "George Strait" },
{ title: "Carried Away", artist: "George Strait" },
{ title: "I Cross My Heart", artist: "George Strait" },
{ title: "All My Ex's Live in Texas", artist: "George Strait" },
{ title: "The Fireman", artist: "George Strait" },
{ title: "Ocean Front Property", artist: "George Strait" },
{ title: "Write This Down", artist: "George Strait" },
{ title: "Give It Away", artist: "George Strait" },
{ title: "Troubadour", artist: "George Strait" },
{ title: "Love Without End Amen", artist: "George Strait" },
{ title: "I Saw God Today", artist: "George Strait" },
{ title: "Nobody in His Right Mind Would've Left Her", artist: "George Strait" },
{ title: "Run", artist: "George Strait" },
// Garth Brooks
{ title: "Friends in Low Places", artist: "Garth Brooks" },
{ title: "The Thunder Rolls", artist: "Garth Brooks" },
{ title: "The Dance", artist: "Garth Brooks" },
{ title: "If Tomorrow Never Comes", artist: "Garth Brooks" },
{ title: "Ain't Goin Down Til the Sun Comes Up", artist: "Garth Brooks" },
{ title: "Standing Outside the Fire", artist: "Garth Brooks" },
{ title: "The River", artist: "Garth Brooks" },
{ title: "Two of a Kind Workin on a Full House", artist: "Garth Brooks" },
{ title: "Rodeo", artist: "Garth Brooks" },
{ title: "Papa Loved Mama", artist: "Garth Brooks" },
{ title: "Much Too Young to Feel This Damn Old", artist: "Garth Brooks" },
{ title: "Callin Baton Rouge", artist: "Garth Brooks" },
{ title: "What She's Doing Now", artist: "Garth Brooks" },
{ title: "Shameless", artist: "Garth Brooks" },
{ title: "Unanswered Prayers", artist: "Garth Brooks" },
// Shania Twain
{ title: "Man I Feel Like a Woman", artist: "Shania Twain" },
{ title: "You're Still the One", artist: "Shania Twain" },
{ title: "That Don't Impress Me Much", artist: "Shania Twain" },
{ title: "From This Moment On", artist: "Shania Twain" },
{ title: "Any Man of Mine", artist: "Shania Twain" },
{ title: "Whose Bed Have Your Boots Been Under", artist: "Shania Twain" },
{ title: "You've Got a Way", artist: "Shania Twain" },
{ title: "No One Needs to Know", artist: "Shania Twain" },
{ title: "Forever and for Always", artist: "Shania Twain" },
{ title: "Come on Over", artist: "Shania Twain" },
{ title: "Don't Be Stupid", artist: "Shania Twain" },
{ title: "Honey I'm Home", artist: "Shania Twain" },
{ title: "Up", artist: "Shania Twain" },
{ title: "Party for Two", artist: "Shania Twain" },
{ title: "Life's About to Get Good", artist: "Shania Twain" },
// Dierks Bentley
{ title: "Drunk on a Plane", artist: "Dierks Bentley" },
{ title: "5-1-5-0", artist: "Dierks Bentley" },
{ title: "Sideways", artist: "Dierks Bentley" },
{ title: "What Was I Thinkin", artist: "Dierks Bentley" },
{ title: "I Hold On", artist: "Dierks Bentley" },
{ title: "Am I the Only One", artist: "Dierks Bentley" },
{ title: "Every Mile a Memory", artist: "Dierks Bentley" },
{ title: "Somewhere on a Beach", artist: "Dierks Bentley" },
{ title: "Woman Amen", artist: "Dierks Bentley" },
{ title: "Living", artist: "Dierks Bentley" },
{ title: "Come a Little Closer", artist: "Dierks Bentley" },
{ title: "Free and Easy", artist: "Dierks Bentley" },
{ title: "Black", artist: "Dierks Bentley" },
{ title: "Burning Man", artist: "Dierks Bentley" },
{ title: "Beers on Me", artist: "Dierks Bentley" },
// Eric Church
{ title: "Springsteen", artist: "Eric Church" },
{ title: "Drink in My Hand", artist: "Eric Church" },
{ title: "Talladega", artist: "Eric Church" },
{ title: "Like a Wrecking Ball", artist: "Eric Church" },
{ title: "Record Year", artist: "Eric Church" },
{ title: "Give Me Back My Hometown", artist: "Eric Church" },
{ title: "Creepin", artist: "Eric Church" },
{ title: "Smoke a Little Smoke", artist: "Eric Church" },
{ title: "The Outsiders", artist: "Eric Church" },
{ title: "Round Here Buzz", artist: "Eric Church" },
{ title: "Some of It", artist: "Eric Church" },
{ title: "Homeboy", artist: "Eric Church" },
{ title: "Mr. Misunderstood", artist: "Eric Church" },
{ title: "Hell of a View", artist: "Eric Church" },
{ title: "Heart on Fire", artist: "Eric Church" },
// Kacey Musgraves
{ title: "Follow Your Arrow", artist: "Kacey Musgraves" },
{ title: "Merry Go Round", artist: "Kacey Musgraves" },
{ title: "Space Cowboy", artist: "Kacey Musgraves" },
{ title: "Slow Burn", artist: "Kacey Musgraves" },
{ title: "Rainbow", artist: "Kacey Musgraves" },
{ title: "Butterflies", artist: "Kacey Musgraves" },
{ title: "Golden Hour", artist: "Kacey Musgraves" },
{ title: "High Horse", artist: "Kacey Musgraves" },
{ title: "Biscuits", artist: "Kacey Musgraves" },
{ title: "Happy and Sad", artist: "Kacey Musgraves" },
{ title: "Justified", artist: "Kacey Musgraves" },
{ title: "Camera Roll", artist: "Kacey Musgraves" },
{ title: "Pageant Material", artist: "Kacey Musgraves" },
{ title: "Dime Store Cowgirl", artist: "Kacey Musgraves" },
{ title: "Deeper Well", artist: "Kacey Musgraves" },
// Maren Morris
{ title: "The Bones", artist: "Maren Morris" },
{ title: "My Church", artist: "Maren Morris" },
{ title: "GIRL", artist: "Maren Morris" },
{ title: "I Could Use a Love Song", artist: "Maren Morris" },
{ title: "Rich", artist: "Maren Morris" },
{ title: "80s Mercedes", artist: "Maren Morris" },
{ title: "The Middle", artist: "Maren Morris" },
{ title: "Chasing After You", artist: "Maren Morris" },
{ title: "Better Than We Found It", artist: "Maren Morris" },
{ title: "Circles Around This Town", artist: "Maren Morris" },
{ title: "All My Favorite People", artist: "Maren Morris" },
{ title: "A Song for Everything", artist: "Maren Morris" },
{ title: "Common", artist: "Maren Morris" },
{ title: "Dear Hate", artist: "Maren Morris" },
{ title: "Shade", artist: "Maren Morris" },
// Dan + Shay
{ title: "Tequila", artist: "Dan + Shay" },
{ title: "Speechless", artist: "Dan + Shay" },
{ title: "10000 Hours", artist: "Dan + Shay" },
{ title: "From the Ground Up", artist: "Dan + Shay" },
{ title: "Nothin Like You", artist: "Dan + Shay" },
{ title: "19 You + Me", artist: "Dan + Shay" },
{ title: "How Not To", artist: "Dan + Shay" },
{ title: "All to Myself", artist: "Dan + Shay" },
{ title: "Glad You Exist", artist: "Dan + Shay" },
{ title: "I Should Probably Go to Bed", artist: "Dan + Shay" },
{ title: "Keeping Score", artist: "Dan + Shay" },
{ title: "Save Me the Trouble", artist: "Dan + Shay" },
{ title: "Where It Ends", artist: "Dan + Shay" },
{ title: "Steal My Love", artist: "Dan + Shay" },
{ title: "You", artist: "Dan + Shay" },
// Kane Brown
{ title: "Heaven", artist: "Kane Brown" },
{ title: "What Ifs", artist: "Kane Brown" },
{ title: "Lose It", artist: "Kane Brown" },
{ title: "Good as You", artist: "Kane Brown" },
{ title: "Homesick", artist: "Kane Brown" },
{ title: "One Thing Right", artist: "Kane Brown" },
{ title: "Cool Again", artist: "Kane Brown" },
{ title: "Worship You", artist: "Kane Brown" },
{ title: "Like I Love Country Music", artist: "Kane Brown" },
{ title: "Worldwide Beautiful", artist: "Kane Brown" },
{ title: "One Mississippi", artist: "Kane Brown" },
{ title: "Thank God", artist: "Kane Brown" },
{ title: "Bury Me in Georgia", artist: "Kane Brown" },
{ title: "Miles on It", artist: "Kane Brown" },
{ title: "Grand", artist: "Kane Brown" },
// Sam Hunt
{ title: "Body Like a Back Road", artist: "Sam Hunt" },
{ title: "Take Your Time", artist: "Sam Hunt" },
{ title: "House Party", artist: "Sam Hunt" },
{ title: "Leave the Night On", artist: "Sam Hunt" },
{ title: "Break Up in a Small Town", artist: "Sam Hunt" },
{ title: "Kinfolks", artist: "Sam Hunt" },
{ title: "Hard to Forget", artist: "Sam Hunt" },
{ title: "Drinkin Too Much", artist: "Sam Hunt" },
{ title: "23", artist: "Sam Hunt" },
{ title: "Downtown's Dead", artist: "Sam Hunt" },
{ title: "Water Under the Bridge", artist: "Sam Hunt" },
{ title: "Breaking Up Was Easy in the 90s", artist: "Sam Hunt" },
{ title: "Come Over", artist: "Sam Hunt" },
{ title: "Speakers", artist: "Sam Hunt" },
{ title: "Outskirts", artist: "Sam Hunt" },
// Lainey Wilson
{ title: "Heart Like a Truck", artist: "Lainey Wilson" },
{ title: "Watermelon Moonshine", artist: "Lainey Wilson" },
{ title: "Things a Man Oughta Know", artist: "Lainey Wilson" },
{ title: "Wait in the Truck", artist: "Lainey Wilson" },
{ title: "Wildflowers and Wild Horses", artist: "Lainey Wilson" },
{ title: "Hang Tight Honey", artist: "Lainey Wilson" },
{ title: "4x4xU", artist: "Lainey Wilson" },
{ title: "Middle of It", artist: "Lainey Wilson" },
{ title: "Hold My Halo", artist: "Lainey Wilson" },
{ title: "New Friends", artist: "Lainey Wilson" },
{ title: "Smell Like Smoke", artist: "Lainey Wilson" },
{ title: "Country's Cool Again", artist: "Lainey Wilson" },
{ title: "Deviled Eggs", artist: "Lainey Wilson" },
{ title: "Sayin What I'm Thinkin", artist: "Lainey Wilson" },
{ title: "Rolling Stone", artist: "Lainey Wilson" },
// Bailey Zimmerman
{ title: "Fall in Love", artist: "Bailey Zimmerman" },
{ title: "Rock and a Hard Place", artist: "Bailey Zimmerman" },
{ title: "Religiously", artist: "Bailey Zimmerman" },
{ title: "Where It Ends", artist: "Bailey Zimmerman" },
{ title: "Fix Her Up", artist: "Bailey Zimmerman" },
{ title: "Trainwreck", artist: "Bailey Zimmerman" },
{ title: "Holy Smokes", artist: "Bailey Zimmerman" },
{ title: "New to Country", artist: "Bailey Zimmerman" },
{ title: "Change", artist: "Bailey Zimmerman" },
{ title: "Damned", artist: "Bailey Zimmerman" },
// Jelly Roll
{ title: "Save Me", artist: "Jelly Roll" },
{ title: "Need a Favor", artist: "Jelly Roll" },
{ title: "Son of a Sinner", artist: "Jelly Roll" },
{ title: "I Am Not Okay", artist: "Jelly Roll" },
{ title: "Halfway to Hell", artist: "Jelly Roll" },
{ title: "She", artist: "Jelly Roll" },
{ title: "Lonely Road", artist: "Jelly Roll" },
{ title: "Dead Man Walking", artist: "Jelly Roll" },
{ title: "Wild Ones", artist: "Jelly Roll" },
{ title: "Best for Me", artist: "Jelly Roll" },
{ title: "Get By", artist: "Jelly Roll" },
{ title: "Love the Heartless", artist: "Jelly Roll" },
{ title: "Winning Streak", artist: "Jelly Roll" },
{ title: "You", artist: "Jelly Roll" },
{ title: "Behind Bars", artist: "Jelly Roll" },
// Hardy
{ title: "Wait in the Truck", artist: "Hardy" },
{ title: "One Beer", artist: "Hardy" },
{ title: "Rednecker", artist: "Hardy" },
{ title: "Give Heaven Some Hell", artist: "Hardy" },
{ title: "Sold Out", artist: "Hardy" },
{ title: "Beers on Me", artist: "Hardy" },
{ title: "Beer", artist: "Hardy" },
{ title: "Truck Bed", artist: "Hardy" },
{ title: "Quit", artist: "Hardy" },
{ title: "Here Lies Country Music", artist: "Hardy" },
{ title: "Red", artist: "Hardy" },
{ title: "Jack", artist: "Hardy" },
{ title: "Unapologetically Country as Hell", artist: "Hardy" },
{ title: "Screen", artist: "Hardy" },
{ title: "Broken Boy", artist: "Hardy" },
// Parker McCollum
{ title: "Pretty Heart", artist: "Parker McCollum" },
{ title: "To Be Loved by You", artist: "Parker McCollum" },
{ title: "Handle on You", artist: "Parker McCollum" },
{ title: "Burn It Down", artist: "Parker McCollum" },
{ title: "Young Man's Blues", artist: "Parker McCollum" },
{ title: "Hell of a Year", artist: "Parker McCollum" },
{ title: "Why Indiana", artist: "Parker McCollum" },
{ title: "Stoned", artist: "Parker McCollum" },
{ title: "Like a Cowboy", artist: "Parker McCollum" },
{ title: "Dallas", artist: "Parker McCollum" },
{ title: "Tails I Lose", artist: "Parker McCollum" },
{ title: "Speed", artist: "Parker McCollum" },
{ title: "What Kinda Man", artist: "Parker McCollum" },
{ title: "Falling Apart", artist: "Parker McCollum" },
{ title: "High Above the Water", artist: "Parker McCollum" },
// Cody Johnson
{ title: "Til You Can't", artist: "Cody Johnson" },
{ title: "With You I Am", artist: "Cody Johnson" },
{ title: "On My Way to You", artist: "Cody Johnson" },
{ title: "Dear Rodeo", artist: "Cody Johnson" },
{ title: "Nothin on You", artist: "Cody Johnson" },
{ title: "Dirt Cheap", artist: "Cody Johnson" },
{ title: "Human", artist: "Cody Johnson" },
{ title: "The Painter", artist: "Cody Johnson" },
{ title: "Wild as You", artist: "Cody Johnson" },
{ title: "Me and My Kind", artist: "Cody Johnson" },
{ title: "Dance Her Home", artist: "Cody Johnson" },
{ title: "Stronger", artist: "Cody Johnson" },
{ title: "Son of a Ramblin Man", artist: "Cody Johnson" },
{ title: "Cowboy Scale of 1 to 10", artist: "Cody Johnson" },
{ title: "I Always Wanted To", artist: "Cody Johnson" },
// Florida Georgia Line
{ title: "Cruise", artist: "Florida Georgia Line" },
{ title: "Meant to Be", artist: "Florida Georgia Line" },
{ title: "H.O.L.Y.", artist: "Florida Georgia Line" },
{ title: "Dirt", artist: "Florida Georgia Line" },
{ title: "Stay", artist: "Florida Georgia Line" },
{ title: "Get Your Shine On", artist: "Florida Georgia Line" },
{ title: "Round Here", artist: "Florida Georgia Line" },
{ title: "This Is How We Roll", artist: "Florida Georgia Line" },
{ title: "May We All", artist: "Florida Georgia Line" },
{ title: "Simple", artist: "Florida Georgia Line" },
{ title: "Talk You Out of It", artist: "Florida Georgia Line" },
{ title: "I Love My Country", artist: "Florida Georgia Line" },
{ title: "Blessings", artist: "Florida Georgia Line" },
{ title: "Confession", artist: "Florida Georgia Line" },
{ title: "Long Live", artist: "Florida Georgia Line" },
// Lady A (Lady Antebellum)
{ title: "Need You Now", artist: "Lady A" },
{ title: "Just a Kiss", artist: "Lady A" },
{ title: "Bartender", artist: "Lady A" },
{ title: "Lookin for a Good Time", artist: "Lady A" },
{ title: "I Run to You", artist: "Lady A" },
{ title: "American Honey", artist: "Lady A" },
{ title: "Downtown", artist: "Lady A" },
{ title: "Compass", artist: "Lady A" },
{ title: "Heart Break", artist: "Lady A" },
{ title: "What If I Never Get Over You", artist: "Lady A" },
{ title: "Hello World", artist: "Lady A" },
{ title: "Our Kind of Love", artist: "Lady A" },
{ title: "You Look Good", artist: "Lady A" },
{ title: "Champagne Night", artist: "Lady A" },
{ title: "Like a Lady", artist: "Lady A" },
// Zac Brown Band
{ title: "Chicken Fried", artist: "Zac Brown Band" },
{ title: "Toes", artist: "Zac Brown Band" },
{ title: "Whatever It Is", artist: "Zac Brown Band" },
{ title: "Knee Deep", artist: "Zac Brown Band" },
{ title: "Free", artist: "Zac Brown Band" },
{ title: "Colder Weather", artist: "Zac Brown Band" },
{ title: "Highway 20 Ride", artist: "Zac Brown Band" },
{ title: "Homegrown", artist: "Zac Brown Band" },
{ title: "Loving You Easy", artist: "Zac Brown Band" },
{ title: "My Old Man", artist: "Zac Brown Band" },
{ title: "As She's Walking Away", artist: "Zac Brown Band" },
{ title: "Jump Right In", artist: "Zac Brown Band" },
{ title: "Same Boat", artist: "Zac Brown Band" },
{ title: "Beautiful Drug", artist: "Zac Brown Band" },
{ title: "Keep Me in Mind", artist: "Zac Brown Band" },
// Old Dominion
{ title: "One Man Band", artist: "Old Dominion" },
{ title: "Break Up with Him", artist: "Old Dominion" },
{ title: "No Such Thing as a Broken Heart", artist: "Old Dominion" },
{ title: "Written in the Sand", artist: "Old Dominion" },
{ title: "Make It Sweet", artist: "Old Dominion" },
{ title: "Snapback", artist: "Old Dominion" },
{ title: "Song for Another Time", artist: "Old Dominion" },
{ title: "Hotel Key", artist: "Old Dominion" },
{ title: "Some People Do", artist: "Old Dominion" },
{ title: "I Was on a Boat That Day", artist: "Old Dominion" },
{ title: "Happy Endings", artist: "Old Dominion" },
{ title: "No Hard Feelings", artist: "Old Dominion" },
{ title: "Stars", artist: "Old Dominion" },
{ title: "Memory Lane", artist: "Old Dominion" },
{ title: "Hear You Now", artist: "Old Dominion" },
// Walker Hayes
{ title: "Fancy Like", artist: "Walker Hayes" },
{ title: "AA", artist: "Walker Hayes" },
{ title: "Y'all Life", artist: "Walker Hayes" },
{ title: "Craig", artist: "Walker Hayes" },
{ title: "Don't Let Her", artist: "Walker Hayes" },
{ title: "Brianna", artist: "Walker Hayes" },
{ title: "90s Country", artist: "Walker Hayes" },
{ title: "U Gurl", artist: "Walker Hayes" },
{ title: "Drink One for Me", artist: "Walker Hayes" },
{ title: "Be a Bro", artist: "Walker Hayes" },
// Jordan Davis
{ title: "Buy Dirt", artist: "Jordan Davis" },
{ title: "Singles You Up", artist: "Jordan Davis" },
{ title: "Slow Dance in a Parking Lot", artist: "Jordan Davis" },
{ title: "Almost Maybes", artist: "Jordan Davis" },
{ title: "Next Thing You Know", artist: "Jordan Davis" },
{ title: "What My World Spins Around", artist: "Jordan Davis" },
{ title: "More Than I Know", artist: "Jordan Davis" },
{ title: "Take It from Me", artist: "Jordan Davis" },
{ title: "Tucked Away", artist: "Jordan Davis" },
{ title: "Going Around", artist: "Jordan Davis" },
// Darius Rucker
{ title: "Wagon Wheel", artist: "Darius Rucker" },
{ title: "Don't Think I Don't Think About It", artist: "Darius Rucker" },
{ title: "Alright", artist: "Darius Rucker" },
{ title: "It Won't Be Like This for Long", artist: "Darius Rucker" },
{ title: "Come Back Song", artist: "Darius Rucker" },
{ title: "This", artist: "Darius Rucker" },
{ title: "History in the Making", artist: "Darius Rucker" },
{ title: "Radio", artist: "Darius Rucker" },
{ title: "Homegrown Honey", artist: "Darius Rucker" },
{ title: "If I Told You", artist: "Darius Rucker" },
{ title: "For the First Time", artist: "Darius Rucker" },
{ title: "Beers and Sunshine", artist: "Darius Rucker" },
// Lee Brice
{ title: "I Drive Your Truck", artist: "Lee Brice" },
{ title: "I Don't Dance", artist: "Lee Brice" },
{ title: "Drinking Class", artist: "Lee Brice" },
{ title: "Hard to Love", artist: "Lee Brice" },
{ title: "Love Like Crazy", artist: "Lee Brice" },
{ title: "A Woman Like You", artist: "Lee Brice" },
{ title: "Rumor", artist: "Lee Brice" },
{ title: "One of Them Girls", artist: "Lee Brice" },
{ title: "Memory I Don't Mess With", artist: "Lee Brice" },
{ title: "Soul", artist: "Lee Brice" },
{ title: "Boy", artist: "Lee Brice" },
{ title: "That Don't Sound Like You", artist: "Lee Brice" },
// Dustin Lynch
{ title: "Small Town Boy", artist: "Dustin Lynch" },
{ title: "Cowboys and Angels", artist: "Dustin Lynch" },
{ title: "Where It's At", artist: "Dustin Lynch" },
{ title: "Mind Reader", artist: "Dustin Lynch" },
{ title: "Seein Red", artist: "Dustin Lynch" },
{ title: "Good Girl", artist: "Dustin Lynch" },
{ title: "Hell of a Night", artist: "Dustin Lynch" },
{ title: "Ridin Roads", artist: "Dustin Lynch" },
{ title: "Party Mode", artist: "Dustin Lynch" },
{ title: "Momma's House", artist: "Dustin Lynch" },
// Brett Young
{ title: "In Case You Didn't Know", artist: "Brett Young" },
{ title: "Mercy", artist: "Brett Young" },
{ title: "Sleep Without You", artist: "Brett Young" },
{ title: "Like I Loved You", artist: "Brett Young" },
{ title: "Here Tonight", artist: "Brett Young" },
{ title: "Catch", artist: "Brett Young" },
{ title: "Lady", artist: "Brett Young" },
{ title: "Not Yet", artist: "Brett Young" },
{ title: "Weekends Look a Little Different These Days", artist: "Brett Young" },
{ title: "You Ain't Here to Kiss Me", artist: "Brett Young" },
// Jon Pardi
{ title: "Dirt on My Boots", artist: "Jon Pardi" },
{ title: "Heartache Medication", artist: "Jon Pardi" },
{ title: "Head Over Boots", artist: "Jon Pardi" },
{ title: "Night Shift", artist: "Jon Pardi" },
{ title: "Tequila Little Time", artist: "Jon Pardi" },
{ title: "Heartache on the Dance Floor", artist: "Jon Pardi" },
{ title: "Ain't Always the Cowboy", artist: "Jon Pardi" },
{ title: "Last Night Lonely", artist: "Jon Pardi" },
{ title: "Up All Night", artist: "Jon Pardi" },
{ title: "She Ain't in It", artist: "Jon Pardi" },
{ title: "Mr. Saturday Night", artist: "Jon Pardi" },
{ title: "Bought the Farm", artist: "Jon Pardi" },
{ title: "Your Heart or Mine", artist: "Jon Pardi" },
{ title: "Fill Er Up", artist: "Jon Pardi" },
{ title: "Neon Light Bar", artist: "Jon Pardi" },
// Midland
{ title: "Drinkin Problem", artist: "Midland" },
{ title: "Burn Out", artist: "Midland" },
{ title: "Make a Little", artist: "Midland" },
{ title: "Mr. Lonely", artist: "Midland" },
{ title: "Cheatin Songs", artist: "Midland" },
{ title: "Lonesome and a Long Way from Home", artist: "Midland" },
{ title: "Put the Hurt on Me", artist: "Midland" },
{ title: "21st Century Honky Tonk American Band", artist: "Midland" },
// Brothers Osborne
{ title: "Stay a Little Longer", artist: "Brothers Osborne" },
{ title: "It Ain't My Fault", artist: "Brothers Osborne" },
{ title: "Shoot Me Straight", artist: "Brothers Osborne" },
{ title: "21 Summer", artist: "Brothers Osborne" },
{ title: "All Night", artist: "Brothers Osborne" },
{ title: "I Don't Remember Me Before You", artist: "Brothers Osborne" },
{ title: "Weed Flower and Waffle House", artist: "Brothers Osborne" },
{ title: "Skeletons", artist: "Brothers Osborne" },
{ title: "Rum", artist: "Brothers Osborne" },
{ title: "Might as Well Be Me", artist: "Brothers Osborne" },
// Chris Young
{ title: "Gettin You Home", artist: "Chris Young" },
{ title: "Tomorrow", artist: "Chris Young" },
{ title: "I'm Comin Over", artist: "Chris Young" },
{ title: "Think of You", artist: "Chris Young" },
{ title: "Losing Sleep", artist: "Chris Young" },
{ title: "Who I Am with You", artist: "Chris Young" },
{ title: "Aw Naw", artist: "Chris Young" },
{ title: "Hangin On", artist: "Chris Young" },
{ title: "Voices", artist: "Chris Young" },
{ title: "You", artist: "Chris Young" },
{ title: "Sober Saturday Night", artist: "Chris Young" },
{ title: "Drowning", artist: "Chris Young" },
{ title: "Raised on Country", artist: "Chris Young" },
{ title: "Famous Friends", artist: "Chris Young" },
{ title: "At the End of a Bar", artist: "Chris Young" },
// Cole Swindell
{ title: "Chillin It", artist: "Cole Swindell" },
{ title: "You Should Be Here", artist: "Cole Swindell" },
{ title: "Ain't Worth the Whiskey", artist: "Cole Swindell" },
{ title: "Hope You Get Lonely Tonight", artist: "Cole Swindell" },
{ title: "Middle of a Memory", artist: "Cole Swindell" },
{ title: "Break Up in the End", artist: "Cole Swindell" },
{ title: "All of It", artist: "Cole Swindell" },
{ title: "Love You Too Late", artist: "Cole Swindell" },
{ title: "Single Saturday Night", artist: "Cole Swindell" },
{ title: "She Had Me at Heads Carolina", artist: "Cole Swindell" },
{ title: "Let Me See Ya Girl", artist: "Cole Swindell" },
{ title: "Flatliner", artist: "Cole Swindell" },
// Scotty McCreery
{ title: "Five More Minutes", artist: "Scotty McCreery" },
{ title: "This Is It", artist: "Scotty McCreery" },
{ title: "In Between", artist: "Scotty McCreery" },
{ title: "Damn Strait", artist: "Scotty McCreery" },
{ title: "You Time", artist: "Scotty McCreery" },
{ title: "I Love You This Big", artist: "Scotty McCreery" },
{ title: "See You Tonight", artist: "Scotty McCreery" },
{ title: "Cab in a Solo", artist: "Scotty McCreery" },
{ title: "It Matters to Her", artist: "Scotty McCreery" },
{ title: "The Trouble with Girls", artist: "Scotty McCreery" },
// Tyler Childers
{ title: "Feathered Indians", artist: "Tyler Childers" },
{ title: "Whitehouse Road", artist: "Tyler Childers" },
{ title: "Lady May", artist: "Tyler Childers" },
{ title: "Follow You to Virgie", artist: "Tyler Childers" },
{ title: "Nose on the Grindstone", artist: "Tyler Childers" },
{ title: "House Fire", artist: "Tyler Childers" },
{ title: "All Your'n", artist: "Tyler Childers" },
{ title: "Shake the Frost", artist: "Tyler Childers" },
{ title: "Long Violent History", artist: "Tyler Childers" },
{ title: "In Your Love", artist: "Tyler Childers" },
{ title: "Universal Sound", artist: "Tyler Childers" },
{ title: "Purgatory", artist: "Tyler Childers" },
// Sturgill Simpson
{ title: "Turtles All the Way Down", artist: "Sturgill Simpson" },
{ title: "In Bloom", artist: "Sturgill Simpson" },
{ title: "Call to Arms", artist: "Sturgill Simpson" },
{ title: "I Don't Mind", artist: "Sturgill Simpson" },
{ title: "Brace for Impact", artist: "Sturgill Simpson" },
{ title: "Life of Sin", artist: "Sturgill Simpson" },
{ title: "Keep It Between the Lines", artist: "Sturgill Simpson" },
{ title: "Long White Line", artist: "Sturgill Simpson" },
// Jason Isbell
{ title: "Cover Me Up", artist: "Jason Isbell" },
{ title: "If We Were Vampires", artist: "Jason Isbell" },
{ title: "24 Frames", artist: "Jason Isbell" },
{ title: "Elephant", artist: "Jason Isbell" },
{ title: "Something More Than Free", artist: "Jason Isbell" },
{ title: "Dress Blues", artist: "Jason Isbell" },
{ title: "Alabama Pines", artist: "Jason Isbell" },
{ title: "Traveling Alone", artist: "Jason Isbell" },
{ title: "Speed Trap Town", artist: "Jason Isbell" },
{ title: "Last of My Kind", artist: "Jason Isbell" },
{ title: "Hope the High Road", artist: "Jason Isbell" },
{ title: "Dreamsicle", artist: "Jason Isbell" },
// Alan Jackson
{ title: "Chattahoochee", artist: "Alan Jackson" },
{ title: "Don't Rock the Jukebox", artist: "Alan Jackson" },
{ title: "Drive", artist: "Alan Jackson" },
{ title: "It's Five O'Clock Somewhere", artist: "Alan Jackson" },
{ title: "Remember When", artist: "Alan Jackson" },
{ title: "Where Were You When the World Stopped Turning", artist: "Alan Jackson" },
{ title: "Gone Country", artist: "Alan Jackson" },
{ title: "Here in the Real World", artist: "Alan Jackson" },
{ title: "Livin on Love", artist: "Alan Jackson" },
{ title: "Good Time", artist: "Alan Jackson" },
{ title: "Chasin That Neon Rainbow", artist: "Alan Jackson" },
{ title: "Mercury Blues", artist: "Alan Jackson" },
{ title: "I Still Like Bologna", artist: "Alan Jackson" },
{ title: "Small Town Southern Man", artist: "Alan Jackson" },
{ title: "Way Down Yonder on the Chattahoochee", artist: "Alan Jackson" },
// Brad Paisley
{ title: "Mud on the Tires", artist: "Brad Paisley" },
{ title: "Alcohol", artist: "Brad Paisley" },
{ title: "Online", artist: "Brad Paisley" },
{ title: "She's Everything", artist: "Brad Paisley" },
{ title: "I'm Gonna Miss Her", artist: "Brad Paisley" },
{ title: "Then", artist: "Brad Paisley" },
{ title: "Water", artist: "Brad Paisley" },
{ title: "Whiskey Lullaby", artist: "Brad Paisley" },
{ title: "Waitin on a Woman", artist: "Brad Paisley" },
{ title: "Letter to Me", artist: "Brad Paisley" },
{ title: "Wrapped Around", artist: "Brad Paisley" },
{ title: "This Is Country Music", artist: "Brad Paisley" },
{ title: "River Bank", artist: "Brad Paisley" },
{ title: "Remind Me", artist: "Brad Paisley" },
{ title: "Beat This Summer", artist: "Brad Paisley" },
// Toby Keith
{ title: "Courtesy of the Red White and Blue", artist: "Toby Keith" },
{ title: "Should've Been a Cowboy", artist: "Toby Keith" },
{ title: "Red Solo Cup", artist: "Toby Keith" },
{ title: "I Love This Bar", artist: "Toby Keith" },
{ title: "Beer for My Horses", artist: "Toby Keith" },
{ title: "As Good as I Once Was", artist: "Toby Keith" },
{ title: "How Do You Like Me Now", artist: "Toby Keith" },
{ title: "Whiskey Girl", artist: "Toby Keith" },
{ title: "American Soldier", artist: "Toby Keith" },
{ title: "Made in America", artist: "Toby Keith" },
{ title: "A Little Too Late", artist: "Toby Keith" },
{ title: "Drinks After Work", artist: "Toby Keith" },
{ title: "My List", artist: "Toby Keith" },
{ title: "Who's That Man", artist: "Toby Keith" },
{ title: "Get Drunk and Be Somebody", artist: "Toby Keith" },
// Reba McEntire
{ title: "Fancy", artist: "Reba McEntire" },
{ title: "The Night the Lights Went Out in Georgia", artist: "Reba McEntire" },
{ title: "Is There Life Out There", artist: "Reba McEntire" },
{ title: "Consider Me Gone", artist: "Reba McEntire" },
{ title: "Does He Love You", artist: "Reba McEntire" },
{ title: "Turn On the Radio", artist: "Reba McEntire" },
{ title: "Whoever's in New England", artist: "Reba McEntire" },
{ title: "The Greatest Man I Never Knew", artist: "Reba McEntire" },
{ title: "I'm a Survivor", artist: "Reba McEntire" },
{ title: "Somebody", artist: "Reba McEntire" },
{ title: "Little Rock", artist: "Reba McEntire" },
{ title: "For My Broken Heart", artist: "Reba McEntire" },
// Faith Hill
{ title: "This Kiss", artist: "Faith Hill" },
{ title: "Breathe", artist: "Faith Hill" },
{ title: "There You'll Be", artist: "Faith Hill" },
{ title: "The Way You Love Me", artist: "Faith Hill" },
{ title: "Cry", artist: "Faith Hill" },
{ title: "Wild One", artist: "Faith Hill" },
{ title: "It Matters to Me", artist: "Faith Hill" },
{ title: "Mississippi Girl", artist: "Faith Hill" },
{ title: "Piece of My Heart", artist: "Faith Hill" },
{ title: "Like We Never Loved at All", artist: "Faith Hill" },
// Martina McBride
{ title: "Independence Day", artist: "Martina McBride" },
{ title: "A Broken Wing", artist: "Martina McBride" },
{ title: "This One's for the Girls", artist: "Martina McBride" },
{ title: "Concrete Angel", artist: "Martina McBride" },
{ title: "My Baby Loves Me", artist: "Martina McBride" },
{ title: "I'm Gonna Love You Through It", artist: "Martina McBride" },
{ title: "Blessed", artist: "Martina McBride" },
{ title: "Wild Angels", artist: "Martina McBride" },
{ title: "Valentine", artist: "Martina McBride" },
{ title: "When God Fearin Women Get the Blues", artist: "Martina McBride" },
// Little Big Town
{ title: "Pontoon", artist: "Little Big Town" },
{ title: "Girl Crush", artist: "Little Big Town" },
{ title: "Better Man", artist: "Little Big Town" },
{ title: "Boondocks", artist: "Little Big Town" },
{ title: "Day Drinking", artist: "Little Big Town" },
{ title: "Tornado", artist: "Little Big Town" },
{ title: "Happy People", artist: "Little Big Town" },
{ title: "Good as Gone", artist: "Little Big Town" },
{ title: "Little White Church", artist: "Little Big Town" },
{ title: "Wine Beer Whiskey", artist: "Little Big Town" },
// Hank Williams
{ title: "Your Cheatin Heart", artist: "Hank Williams" },
{ title: "I'm So Lonesome I Could Cry", artist: "Hank Williams" },
{ title: "Hey Good Lookin", artist: "Hank Williams" },
{ title: "Jambalaya", artist: "Hank Williams" },
{ title: "Cold Cold Heart", artist: "Hank Williams" },
{ title: "I Saw the Light", artist: "Hank Williams" },
{ title: "Lovesick Blues", artist: "Hank Williams" },
{ title: "Move It on Over", artist: "Hank Williams" },
{ title: "Long Gone Lonesome Blues", artist: "Hank Williams" },
{ title: "Kaw-Liga", artist: "Hank Williams" },
// Hank Williams Jr.
{ title: "All My Rowdy Friends Are Coming Over Tonight", artist: "Hank Williams Jr." },
{ title: "Family Tradition", artist: "Hank Williams Jr." },
{ title: "A Country Boy Can Survive", artist: "Hank Williams Jr." },
{ title: "Born to Boogie", artist: "Hank Williams Jr." },
{ title: "Whiskey Bent and Hell Bound", artist: "Hank Williams Jr." },
{ title: "Dixie on My Mind", artist: "Hank Williams Jr." },
{ title: "All My Rowdy Friends Have Settled Down", artist: "Hank Williams Jr." },
{ title: "Texas Women", artist: "Hank Williams Jr." },
// Merle Haggard
{ title: "Mama Tried", artist: "Merle Haggard" },
{ title: "Okie from Muskogee", artist: "Merle Haggard" },
{ title: "The Fightin Side of Me", artist: "Merle Haggard" },
{ title: "Sing Me Back Home", artist: "Merle Haggard" },
{ title: "That's the Way Love Goes", artist: "Merle Haggard" },
{ title: "Workin Man Blues", artist: "Merle Haggard" },
{ title: "Today I Started Loving You Again", artist: "Merle Haggard" },
{ title: "Branded Man", artist: "Merle Haggard" },
{ title: "Silver Wings", artist: "Merle Haggard" },
{ title: "If We Make It Through December", artist: "Merle Haggard" },
// Waylon Jennings
{ title: "Good Hearted Woman", artist: "Waylon Jennings" },
{ title: "Luckenbach Texas", artist: "Waylon Jennings" },
{ title: "Are You Sure Hank Done It This Way", artist: "Waylon Jennings" },
{ title: "I Ain't Living Long Like This", artist: "Waylon Jennings" },
{ title: "Mammas Don't Let Your Babies Grow Up to Be Cowboys", artist: "Waylon Jennings" },
{ title: "Amanda", artist: "Waylon Jennings" },
{ title: "The Dukes of Hazzard Theme", artist: "Waylon Jennings" },
{ title: "Lonesome On'ry and Mean", artist: "Waylon Jennings" },
{ title: "Bob Wills Is Still the King", artist: "Waylon Jennings" },
{ title: "Rainy Day Woman", artist: "Waylon Jennings" },
// Patsy Cline
{ title: "Crazy", artist: "Patsy Cline" },
{ title: "I Fall to Pieces", artist: "Patsy Cline" },
{ title: "Walkin After Midnight", artist: "Patsy Cline" },
{ title: "Sweet Dreams", artist: "Patsy Cline" },
{ title: "She's Got You", artist: "Patsy Cline" },
{ title: "Back in Baby's Arms", artist: "Patsy Cline" },
{ title: "Leavin on Your Mind", artist: "Patsy Cline" },
{ title: "Why Can't He Be You", artist: "Patsy Cline" },
// John Denver
{ title: "Take Me Home Country Roads", artist: "John Denver" },
{ title: "Sunshine on My Shoulders", artist: "John Denver" },
{ title: "Rocky Mountain High", artist: "John Denver" },
{ title: "Annie's Song", artist: "John Denver" },
{ title: "Thank God I'm a Country Boy", artist: "John Denver" },
{ title: "Leaving on a Jet Plane", artist: "John Denver" },
{ title: "Calypso", artist: "John Denver" },
{ title: "Back Home Again", artist: "John Denver" },
{ title: "I'm Sorry", artist: "John Denver" },
{ title: "Perhaps Love", artist: "John Denver" },
// Randy Travis
{ title: "Forever and Ever Amen", artist: "Randy Travis" },
{ title: "Diggin Up Bones", artist: "Randy Travis" },
{ title: "On the Other Hand", artist: "Randy Travis" },
{ title: "Deeper Than the Holler", artist: "Randy Travis" },
{ title: "I Told You So", artist: "Randy Travis" },
{ title: "Three Wooden Crosses", artist: "Randy Travis" },
{ title: "1982", artist: "Randy Travis" },
{ title: "Hard Rock Bottom of Your Heart", artist: "Randy Travis" },
{ title: "Storms of Life", artist: "Randy Travis" },
{ title: "Is It Still Over", artist: "Randy Travis" },
// Brooks and Dunn
{ title: "Boot Scootin Boogie", artist: "Brooks and Dunn" },
{ title: "Neon Moon", artist: "Brooks and Dunn" },
{ title: "My Maria", artist: "Brooks and Dunn" },
{ title: "Ain't Nothing Bout You", artist: "Brooks and Dunn" },
{ title: "Red Dirt Road", artist: "Brooks and Dunn" },
{ title: "Believe", artist: "Brooks and Dunn" },
{ title: "Brand New Man", artist: "Brooks and Dunn" },
{ title: "Only in America", artist: "Brooks and Dunn" },
{ title: "You're Gonna Miss Me When I'm Gone", artist: "Brooks and Dunn" },
{ title: "Husbands and Wives", artist: "Brooks and Dunn" },
// Alabama
{ title: "Mountain Music", artist: "Alabama" },
{ title: "Dixieland Delight", artist: "Alabama" },
{ title: "Song of the South", artist: "Alabama" },
{ title: "Love in the First Degree", artist: "Alabama" },
{ title: "If You're Gonna Play in Texas", artist: "Alabama" },
{ title: "Feels So Right", artist: "Alabama" },
{ title: "Tennessee River", artist: "Alabama" },
{ title: "Cheap Seats", artist: "Alabama" },
{ title: "Roll On", artist: "Alabama" },
{ title: "Born Country", artist: "Alabama" },
// Travis Tritt
{ title: "It's a Great Day to Be Alive", artist: "Travis Tritt" },
{ title: "Here's a Quarter", artist: "Travis Tritt" },
{ title: "T-R-O-U-B-L-E", artist: "Travis Tritt" },
{ title: "Anymore", artist: "Travis Tritt" },
{ title: "Best of Intentions", artist: "Travis Tritt" },
{ title: "Country Ain't Country", artist: "Travis Tritt" },
{ title: "Foolish Pride", artist: "Travis Tritt" },
{ title: "Can I Trust You with My Heart", artist: "Travis Tritt" },
// Vince Gill
{ title: "When I Call Your Name", artist: "Vince Gill" },
{ title: "Go Rest High on That Mountain", artist: "Vince Gill" },
{ title: "I Still Believe in You", artist: "Vince Gill" },
{ title: "Don't Let Our Love Start Slippin Away", artist: "Vince Gill" },
{ title: "Look at Us", artist: "Vince Gill" },
{ title: "Whenever You Come Around", artist: "Vince Gill" },
{ title: "One More Last Chance", artist: "Vince Gill" },
{ title: "Pocket Full of Gold", artist: "Vince Gill" },
// Kenny Rogers
{ title: "The Gambler", artist: "Kenny Rogers" },
{ title: "Lucille", artist: "Kenny Rogers" },
{ title: "Coward of the County", artist: "Kenny Rogers" },
{ title: "Lady", artist: "Kenny Rogers" },
{ title: "Islands in the Stream", artist: "Kenny Rogers" },
{ title: "Through the Years", artist: "Kenny Rogers" },
{ title: "She Believes in Me", artist: "Kenny Rogers" },
{ title: "Ruby Don't Take Your Love to Town", artist: "Kenny Rogers" },
{ title: "You Decorated My Life", artist: "Kenny Rogers" },
{ title: "Daytime Friends", artist: "Kenny Rogers" },
// Kris Kristofferson
{ title: "Me and Bobby McGee", artist: "Kris Kristofferson" },
{ title: "Sunday Mornin Comin Down", artist: "Kris Kristofferson" },
{ title: "Help Me Make It Through the Night", artist: "Kris Kristofferson" },
{ title: "For the Good Times", artist: "Kris Kristofferson" },
{ title: "Why Me", artist: "Kris Kristofferson" },
{ title: "Lovin Her Was Easier", artist: "Kris Kristofferson" },
{ title: "The Silver Tongued Devil and I", artist: "Kris Kristofferson" },
// Loretta Lynn
{ title: "Coal Miner's Daughter", artist: "Loretta Lynn" },
{ title: "You Ain't Woman Enough", artist: "Loretta Lynn" },
{ title: "Don't Come Home A-Drinkin", artist: "Loretta Lynn" },
{ title: "The Pill", artist: "Loretta Lynn" },
{ title: "Fist City", artist: "Loretta Lynn" },
{ title: "Rated X", artist: "Loretta Lynn" },
{ title: "One's on the Way", artist: "Loretta Lynn" },
{ title: "Somebody Somewhere", artist: "Loretta Lynn" },
// Charley Pride
{ title: "Kiss an Angel Good Mornin", artist: "Charley Pride" },
{ title: "Is Anybody Goin to San Antone", artist: "Charley Pride" },
{ title: "Mountain of Love", artist: "Charley Pride" },
{ title: "All I Have to Offer You Is Me", artist: "Charley Pride" },
{ title: "Crystal Chandeliers", artist: "Charley Pride" },
{ title: "Just Between You and Me", artist: "Charley Pride" },
// Glen Campbell
{ title: "Rhinestone Cowboy", artist: "Glen Campbell" },
{ title: "Wichita Lineman", artist: "Glen Campbell" },
{ title: "Galveston", artist: "Glen Campbell" },
{ title: "By the Time I Get to Phoenix", artist: "Glen Campbell" },
{ title: "Southern Nights", artist: "Glen Campbell" },
{ title: "Gentle on My Mind", artist: "Glen Campbell" },
{ title: "Try a Little Kindness", artist: "Glen Campbell" },
{ title: "Country Boy", artist: "Glen Campbell" },
// George Jones
{ title: "He Stopped Loving Her Today", artist: "George Jones" },
{ title: "The Grand Tour", artist: "George Jones" },
{ title: "She Thinks I Still Care", artist: "George Jones" },
{ title: "White Lightning", artist: "George Jones" },
{ title: "Choices", artist: "George Jones" },
{ title: "The Race Is On", artist: "George Jones" },
{ title: "Who's Gonna Fill Their Shoes", artist: "George Jones" },
{ title: "Bartender's Blues", artist: "George Jones" },
// Tammy Wynette
{ title: "Stand by Your Man", artist: "Tammy Wynette" },
{ title: "D-I-V-O-R-C-E", artist: "Tammy Wynette" },
{ title: "Golden Ring", artist: "Tammy Wynette" },
{ title: "Your Good Girl's Gonna Go Bad", artist: "Tammy Wynette" },
{ title: "Til I Can Make It on My Own", artist: "Tammy Wynette" },
{ title: "I Don't Wanna Play House", artist: "Tammy Wynette" },
// Conway Twitty
{ title: "Hello Darlin", artist: "Conway Twitty" },
{ title: "It's Only Make Believe", artist: "Conway Twitty" },
{ title: "I'd Love to Lay You Down", artist: "Conway Twitty" },
{ title: "Tight Fittin Jeans", artist: "Conway Twitty" },
{ title: "That's My Job", artist: "Conway Twitty" },
{ title: "Louisiana Woman Mississippi Man", artist: "Conway Twitty" },
// Turnpike Troubadours
{ title: "Gin Smoke Lies", artist: "Turnpike Troubadours" },
{ title: "Diamonds and Gasoline", artist: "Turnpike Troubadours" },
{ title: "Good Lord Lorrie", artist: "Turnpike Troubadours" },
{ title: "Every Girl", artist: "Turnpike Troubadours" },
{ title: "Long Hot Summer Day", artist: "Turnpike Troubadours" },
{ title: "The Bird Hunters", artist: "Turnpike Troubadours" },
{ title: "Bossier City", artist: "Turnpike Troubadours" },
{ title: "Blue Star", artist: "Turnpike Troubadours" },
// Colter Wall
{ title: "Sleeping on the Blacktop", artist: "Colter Wall" },
{ title: "Kate McCannon", artist: "Colter Wall" },
{ title: "Thirteen Silver Dollars", artist: "Colter Wall" },
{ title: "The Devil Wears a Suit and Tie", artist: "Colter Wall" },
{ title: "Big Iron", artist: "Colter Wall" },
{ title: "Cowpoke", artist: "Colter Wall" },
{ title: "Thinkin on a Woman", artist: "Colter Wall" },
{ title: "Caroline", artist: "Colter Wall" },
// Tyler Hubbard
{ title: "5 Foot 9", artist: "Tyler Hubbard" },
{ title: "Dancin in the Country", artist: "Tyler Hubbard" },
{ title: "35's", artist: "Tyler Hubbard" },
{ title: "Wish You Would", artist: "Tyler Hubbard" },
{ title: "Back Then Right Now", artist: "Tyler Hubbard" },
{ title: "Park It", artist: "Tyler Hubbard" },
// Russell Dickerson
{ title: "Yours", artist: "Russell Dickerson" },
{ title: "Blue Tacoma", artist: "Russell Dickerson" },
{ title: "Every Little Thing", artist: "Russell Dickerson" },
{ title: "Love You Like I Used To", artist: "Russell Dickerson" },
{ title: "She Likes It", artist: "Russell Dickerson" },
{ title: "God Gave Me a Girl", artist: "Russell Dickerson" },
// Mitchell Tenpenny
{ title: "Drunk Me", artist: "Mitchell Tenpenny" },
{ title: "Truth About You", artist: "Mitchell Tenpenny" },
{ title: "Alcohol You Later", artist: "Mitchell Tenpenny" },
{ title: "Bucket List", artist: "Mitchell Tenpenny" },
{ title: "Walk Like Him", artist: "Mitchell Tenpenny" },
// Riley Green
{ title: "I Wish Grandpas Never Died", artist: "Riley Green" },
{ title: "There Was This Girl", artist: "Riley Green" },
{ title: "Different Round Here", artist: "Riley Green" },
{ title: "If It Wasn't for Trucks", artist: "Riley Green" },
{ title: "Half of Me", artist: "Riley Green" },
{ title: "Outlaws Like Us", artist: "Riley Green" },
{ title: "Mississippi or Me", artist: "Riley Green" },
{ title: "Hell of a Way to Go", artist: "Riley Green" },
// Ashley McBryde
{ title: "A Little Dive Bar in Dahlonega", artist: "Ashley McBryde" },
{ title: "One Night Standards", artist: "Ashley McBryde" },
{ title: "Martha Divine", artist: "Ashley McBryde" },
{ title: "Girl Goin Nowhere", artist: "Ashley McBryde" },
{ title: "Never Wanted to Be That Girl", artist: "Ashley McBryde" },
{ title: "Light on in the Kitchen", artist: "Ashley McBryde" },
{ title: "Sparrow", artist: "Ashley McBryde" },
// Gabby Barrett
{ title: "I Hope", artist: "Gabby Barrett" },
{ title: "The Good Ones", artist: "Gabby Barrett" },
{ title: "Pick Me Up", artist: "Gabby Barrett" },
{ title: "Footprints on the Moon", artist: "Gabby Barrett" },
{ title: "Glory Days", artist: "Gabby Barrett" },
// Chris Lane
{ title: "Fix", artist: "Chris Lane" },
{ title: "Big Big Plans", artist: "Chris Lane" },
{ title: "I Don't Know About You", artist: "Chris Lane" },
{ title: "Take Back Home Girl", artist: "Chris Lane" },
{ title: "Fill Them Boots", artist: "Chris Lane" },
// Chase Rice
{ title: "Eyes on You", artist: "Chase Rice" },
{ title: "Lonely If You Are", artist: "Chase Rice" },
{ title: "Drinkin Beer Talkin God Amen", artist: "Chase Rice" },
{ title: "Ready Set Roll", artist: "Chase Rice" },
{ title: "Ride", artist: "Chase Rice" },
{ title: "Do It Like This", artist: "Chase Rice" },
// Michael Ray
{ title: "Kiss You in the Morning", artist: "Michael Ray" },
{ title: "Think a Little Less", artist: "Michael Ray" },
{ title: "One That Got Away", artist: "Michael Ray" },
{ title: "Her World or Mine", artist: "Michael Ray" },
{ title: "Whiskey and Rain", artist: "Michael Ray" },
// Jake Owen
{ title: "Barefoot Blue Jean Night", artist: "Jake Owen" },
{ title: "Alone with You", artist: "Jake Owen" },
{ title: "Beachin", artist: "Jake Owen" },
{ title: "I Was Jack (You Were Diane)", artist: "Jake Owen" },
{ title: "Down to the Honkytonk", artist: "Jake Owen" },
{ title: "American Country Love Song", artist: "Jake Owen" },
{ title: "Homemade", artist: "Jake Owen" },
{ title: "Made for You", artist: "Jake Owen" },
// Billy Currington
{ title: "People Are Crazy", artist: "Billy Currington" },
{ title: "Good Directions", artist: "Billy Currington" },
{ title: "Must Be Doin Somethin Right", artist: "Billy Currington" },
{ title: "Pretty Good at Drinkin Beer", artist: "Billy Currington" },
{ title: "Let Me Down Easy", artist: "Billy Currington" },
{ title: "Hey Girl", artist: "Billy Currington" },
{ title: "Don't It", artist: "Billy Currington" },
// Keith Whitley
{ title: "When You Say Nothing at All", artist: "Keith Whitley" },
{ title: "Don't Close Your Eyes", artist: "Keith Whitley" },
{ title: "I'm No Stranger to the Rain", artist: "Keith Whitley" },
{ title: "I'm Over You", artist: "Keith Whitley" },
{ title: "Miami My Amy", artist: "Keith Whitley" },
// Jamey Johnson
{ title: "In Color", artist: "Jamey Johnson" },
{ title: "High Cost of Living", artist: "Jamey Johnson" },
{ title: "Lead Me Home", artist: "Jamey Johnson" },
{ title: "Between Jennings and Jones", artist: "Jamey Johnson" },
{ title: "Give It Away", artist: "Jamey Johnson" },
// Trace Adkins
{ title: "You're Gonna Miss This", artist: "Trace Adkins" },
{ title: "Honky Tonk Badonkadonk", artist: "Trace Adkins" },
{ title: "Every Light in the House", artist: "Trace Adkins" },
{ title: "Songs About Me", artist: "Trace Adkins" },
{ title: "Ladies Love Country Boys", artist: "Trace Adkins" },
{ title: "Arlington", artist: "Trace Adkins" },
// Eli Young Band
{ title: "Crazy Girl", artist: "Eli Young Band" },
{ title: "Even If It Breaks Your Heart", artist: "Eli Young Band" },
{ title: "Drunk Last Night", artist: "Eli Young Band" },
{ title: "Love Ain't", artist: "Eli Young Band" },
{ title: "Saltwater Gospel", artist: "Eli Young Band" },
// Maddie and Tae
{ title: "Girl in a Country Song", artist: "Maddie and Tae" },
{ title: "Die from a Broken Heart", artist: "Maddie and Tae" },
{ title: "Fly", artist: "Maddie and Tae" },
{ title: "Friends Don't", artist: "Maddie and Tae" },
{ title: "Woman You Got", artist: "Maddie and Tae" },
// Niko Moon
{ title: "Good Time", artist: "Niko Moon" },
{ title: "No Sad Songs", artist: "Niko Moon" },
{ title: "Paradise to Me", artist: "Niko Moon" },
// The Chicks (Dixie Chicks)
{ title: "Wide Open Spaces", artist: "The Chicks" },
{ title: "Not Ready to Make Nice", artist: "The Chicks" },
{ title: "Cowboy Take Me Away", artist: "The Chicks" },
{ title: "Travelin Soldier", artist: "The Chicks" },
{ title: "Goodbye Earl", artist: "The Chicks" },
{ title: "Landslide", artist: "The Chicks" },
{ title: "There's Your Trouble", artist: "The Chicks" },
{ title: "Long Time Gone", artist: "The Chicks" },
{ title: "You Were Mine", artist: "The Chicks" },
{ title: "Tonight the Heartache's on Me", artist: "The Chicks" },
// Jimmie Allen
{ title: "Best Shot", artist: "Jimmie Allen" },
{ title: "Make Me Want To", artist: "Jimmie Allen" },
{ title: "Freedom Was a Highway", artist: "Jimmie Allen" },
{ title: "Down Home", artist: "Jimmie Allen" },
// Easton Corbin
{ title: "A Little More Country Than That", artist: "Easton Corbin" },
{ title: "Roll with It", artist: "Easton Corbin" },
{ title: "Lovin You Is Fun", artist: "Easton Corbin" },
{ title: "Are You with Me", artist: "Easton Corbin" },
// Justin Moore
{ title: "Small Town USA", artist: "Justin Moore" },
{ title: "Lettin the Night Roll", artist: "Justin Moore" },
{ title: "If Heaven Wasn't So Far Away", artist: "Justin Moore" },
{ title: "Til My Last Day", artist: "Justin Moore" },
{ title: "Somebody Else Will", artist: "Justin Moore" },
{ title: "You Look Like I Need a Drink", artist: "Justin Moore" },
{ title: "Point at You", artist: "Justin Moore" },
{ title: "Kinda Don't Care", artist: "Justin Moore" },
// Morgan Wade
{ title: "Wilder Days", artist: "Morgan Wade" },
{ title: "Run", artist: "Morgan Wade" },
{ title: "The Night", artist: "Morgan Wade" },
{ title: "Fall in Love with Me", artist: "Morgan Wade" },
{ title: "Last Cigarette", artist: "Morgan Wade" },
// Josh Turner
{ title: "Long Black Train", artist: "Josh Turner" },
{ title: "Your Man", artist: "Josh Turner" },
{ title: "Would You Go with Me", artist: "Josh Turner" },
{ title: "Why Don't We Just Dance", artist: "Josh Turner" },
{ title: "Time Is Love", artist: "Josh Turner" },
{ title: "Hometown Girl", artist: "Josh Turner" },
// Dwight Yoakam
{ title: "Guitars Cadillacs", artist: "Dwight Yoakam" },
{ title: "Honky Tonk Man", artist: "Dwight Yoakam" },
{ title: "Streets of Bakersfield", artist: "Dwight Yoakam" },
{ title: "Thousand Miles from Nowhere", artist: "Dwight Yoakam" },
{ title: "Fast as You", artist: "Dwight Yoakam" },
{ title: "I Sang Dixie", artist: "Dwight Yoakam" },
{ title: "Little Sister", artist: "Dwight Yoakam" },
// Emmylou Harris
{ title: "Together Again", artist: "Emmylou Harris" },
{ title: "If I Could Only Win Your Love", artist: "Emmylou Harris" },
{ title: "Beneath Still Waters", artist: "Emmylou Harris" },
{ title: "To Daddy", artist: "Emmylou Harris" },
{ title: "Blue Kentucky Girl", artist: "Emmylou Harris" },
{ title: "Making Believe", artist: "Emmylou Harris" },
// Lee Ann Womack
{ title: "I Hope You Dance", artist: "Lee Ann Womack" },
{ title: "The Fool", artist: "Lee Ann Womack" },
{ title: "A Little Past Little Rock", artist: "Lee Ann Womack" },
{ title: "I May Hate Myself in the Morning", artist: "Lee Ann Womack" },
{ title: "Am I the Only Thing That You've Done Wrong", artist: "Lee Ann Womack" },
// Rodney Atkins
{ title: "If You're Going Through Hell", artist: "Rodney Atkins" },
{ title: "Watching You", artist: "Rodney Atkins" },
{ title: "It's America", artist: "Rodney Atkins" },
{ title: "These Are My People", artist: "Rodney Atkins" },
{ title: "Take a Back Road", artist: "Rodney Atkins" },
// Craig Morgan
{ title: "That's What I Love About Sunday", artist: "Craig Morgan" },
{ title: "Redneck Yacht Club", artist: "Craig Morgan" },
{ title: "International Harvester", artist: "Craig Morgan" },
{ title: "Bonfire", artist: "Craig Morgan" },
// Brantley Gilbert
{ title: "Bottoms Up", artist: "Brantley Gilbert" },
{ title: "One Hell of an Amen", artist: "Brantley Gilbert" },
{ title: "Country Must Be Country Wide", artist: "Brantley Gilbert" },
{ title: "You Don't Know Her Like I Do", artist: "Brantley Gilbert" },
{ title: "Kick It in the Sticks", artist: "Brantley Gilbert" },
{ title: "My Kind of Crazy", artist: "Brantley Gilbert" },
{ title: "Small Town Throwdown", artist: "Brantley Gilbert" },
{ title: "The Weekend", artist: "Brantley Gilbert" },
{ title: "Fire't Up", artist: "Brantley Gilbert" },
{ title: "What Happens in a Small Town", artist: "Brantley Gilbert" },
// Lil Nas X (country crossover)
{ title: "Old Town Road", artist: "Lil Nas X" },
// Bebe Rexha (country crossover)
{ title: "Meant to Be", artist: "Bebe Rexha" },
// Carly Pearce
{ title: "Every Little Thing", artist: "Carly Pearce" },
{ title: "I Hope You're Happy Now", artist: "Carly Pearce" },
{ title: "Next Girl", artist: "Carly Pearce" },
{ title: "Never Wanted to Be That Girl", artist: "Carly Pearce" },
{ title: "What He Didn't Do", artist: "Carly Pearce" },
{ title: "Dear Miss Loretta", artist: "Carly Pearce" },
{ title: "Diamondback", artist: "Carly Pearce" },
// Tenille Townes
{ title: "Somebody's Daughter", artist: "Tenille Townes" },
{ title: "Jersey on the Wall", artist: "Tenille Townes" },
{ title: "White Horse", artist: "Tenille Townes" },
{ title: "When's It Gonna Happen", artist: "Tenille Townes" },
// Priscilla Block
{ title: "Just About Over You", artist: "Priscilla Block" },
{ title: "Thick Thighs", artist: "Priscilla Block" },
{ title: "My Bar", artist: "Priscilla Block" },
{ title: "I Know a Girl", artist: "Priscilla Block" },
// Ingrid Andress
{ title: "More Hearts Than Mine", artist: "Ingrid Andress" },
{ title: "Lady Like", artist: "Ingrid Andress" },
{ title: "Wishful Drinking", artist: "Ingrid Andress" },
// Elvie Shane
{ title: "My Boy", artist: "Elvie Shane" },
{ title: "County Roads", artist: "Elvie Shane" },
// Nate Smith
{ title: "Whiskey on You", artist: "Nate Smith" },
{ title: "World on Fire", artist: "Nate Smith" },
{ title: "Bulletproof", artist: "Nate Smith" },
{ title: "Through with You", artist: "Nate Smith" },
// Chayce Beckham
{ title: "23", artist: "Chayce Beckham" },
{ title: "Till the Day I Die", artist: "Chayce Beckham" },
{ title: "Talking to Myself", artist: "Chayce Beckham" },
// Tyler Braden
{ title: "Try Losing One", artist: "Tyler Braden" },
{ title: "Devil You Know", artist: "Tyler Braden" },
// Conner Smith
{ title: "Learn from It", artist: "Conner Smith" },
{ title: "Take It Slow", artist: "Conner Smith" },
// Tucker Wetmore
{ title: "Wind Up Missin You", artist: "Tucker Wetmore" },
{ title: "Wine Into Whiskey", artist: "Tucker Wetmore" },
// Wyatt Flores
{ title: "Please Don't Go", artist: "Wyatt Flores" },
{ title: "Half Broke Heart", artist: "Wyatt Flores" },
{ title: "Travelin Kind", artist: "Wyatt Flores" },
// Hailey Whitters
{ title: "Everything She Ain't", artist: "Hailey Whitters" },
{ title: "Fillin My Cup", artist: "Hailey Whitters" },
{ title: "Janice at the Hotel Bar", artist: "Hailey Whitters" },
// Muscadine Bloodline
{ title: "Porch Swing Angel", artist: "Muscadine Bloodline" },
{ title: "WD-40", artist: "Muscadine Bloodline" },
{ title: "Movin On", artist: "Muscadine Bloodline" },
// Cody Jinks
{ title: "Loud and Heavy", artist: "Cody Jinks" },
{ title: "Hippies and Cowboys", artist: "Cody Jinks" },
{ title: "Must Be the Whiskey", artist: "Cody Jinks" },
{ title: "Mamma Song", artist: "Cody Jinks" },
{ title: "Lifers", artist: "Cody Jinks" },
{ title: "Cast No Stones", artist: "Cody Jinks" },
// Charley Crockett
{ title: "Welcome to Hard Times", artist: "Charley Crockett" },
{ title: "Trinity River", artist: "Charley Crockett" },
{ title: "Jamestown Ferry", artist: "Charley Crockett" },
{ title: "I Need Your Love", artist: "Charley Crockett" },
{ title: "Round This World", artist: "Charley Crockett" },
// Chris Janson
{ title: "Buy Me a Boat", artist: "Chris Janson" },
{ title: "Fix a Drink", artist: "Chris Janson" },
{ title: "Good Vibes", artist: "Chris Janson" },
{ title: "Done", artist: "Chris Janson" },
{ title: "Drunk Girl", artist: "Chris Janson" },
// Dillon Carmichael
{ title: "Hot Beer", artist: "Dillon Carmichael" },
{ title: "Son of a", artist: "Dillon Carmichael" },
// Drew Parker
{ title: "While You're Away", artist: "Drew Parker" },
// Ryan Hurd
{ title: "Chasing After You", artist: "Ryan Hurd" },
{ title: "Platonic", artist: "Ryan Hurd" },
{ title: "Every Other Memory", artist: "Ryan Hurd" },
// Parmalee
{ title: "Carolina", artist: "Parmalee" },
{ title: "Take My Name", artist: "Parmalee" },
{ title: "Just the Way", artist: "Parmalee" },
// Granger Smith
{ title: "Backroad Song", artist: "Granger Smith" },
{ title: "Happens Like That", artist: "Granger Smith" },
{ title: "If the Boot Fits", artist: "Granger Smith" },
// Kelsea Ballerini
{ title: "Love Me Like You Mean It", artist: "Kelsea Ballerini" },
{ title: "Peter Pan", artist: "Kelsea Ballerini" },
{ title: "Dibs", artist: "Kelsea Ballerini" },
{ title: "Legends", artist: "Kelsea Ballerini" },
{ title: "Miss Me More", artist: "Kelsea Ballerini" },
{ title: "Hole in the Bottle", artist: "Kelsea Ballerini" },
{ title: "Yeah Boy", artist: "Kelsea Ballerini" },
{ title: "Heartfirst", artist: "Kelsea Ballerini" },
{ title: "If You Go Down", artist: "Kelsea Ballerini" },
{ title: "Blindsided", artist: "Kelsea Ballerini" },
// Lauren Alaina
{ title: "Road Less Traveled", artist: "Lauren Alaina" },
{ title: "Like My Mother Does", artist: "Lauren Alaina" },
{ title: "What Ifs", artist: "Lauren Alaina" },
{ title: "Getting Good", artist: "Lauren Alaina" },
{ title: "Getting Over Him", artist: "Lauren Alaina" },
// RaeLynn
{ title: "God Made Girls", artist: "RaeLynn" },
{ title: "Love Triangle", artist: "RaeLynn" },
{ title: "Lonely Call", artist: "RaeLynn" },
// Tyler Farr
{ title: "Redneck Crazy", artist: "Tyler Farr" },
{ title: "Whiskey in My Water", artist: "Tyler Farr" },
{ title: "A Guy Walks Into a Bar", artist: "Tyler Farr" },
// Canaan Smith
{ title: "Love You Like That", artist: "Canaan Smith" },
{ title: "Hole in a Bottle", artist: "Canaan Smith" },
// David Lee Murphy
{ title: "Dust on the Bottle", artist: "David Lee Murphy" },
{ title: "Everything's Gonna Be Alright", artist: "David Lee Murphy" },
// Brent Cobb
{ title: "Ain't a Road Too Long", artist: "Brent Cobb" },
{ title: "Solving Problems", artist: "Brent Cobb" },
// Kameron Marlowe
{ title: "Giving You Up", artist: "Kameron Marlowe" },
{ title: "Strangers", artist: "Kameron Marlowe" },
{ title: "Steady Heart", artist: "Kameron Marlowe" },
// Sierra Ferrell
{ title: "Jeremiah", artist: "Sierra Ferrell" },
{ title: "In Dreams", artist: "Sierra Ferrell" },
{ title: "Dollar Bill Bar", artist: "Sierra Ferrell" },
// Flatland Cavalry
{ title: "A Life Where We Work Out", artist: "Flatland Cavalry" },
{ title: "Dancin Around a Fire", artist: "Flatland Cavalry" },
{ title: "Mountain Song", artist: "Flatland Cavalry" },
{ title: "Sleeping Alone", artist: "Flatland Cavalry" },
// Whiskey Myers
{ title: "Stone", artist: "Whiskey Myers" },
{ title: "Ballad of a Southern Man", artist: "Whiskey Myers" },
{ title: "Broken Window Serenade", artist: "Whiskey Myers" },
{ title: "Virginia", artist: "Whiskey Myers" },
{ title: "Gasoline", artist: "Whiskey Myers" },
{ title: "Bury My Bones", artist: "Whiskey Myers" },
// Jameson Rodgers
{ title: "Some Girls", artist: "Jameson Rodgers" },
{ title: "Cold Beer Calling My Name", artist: "Jameson Rodgers" },
// Ian Munsick
{ title: "Long Live Cowgirls", artist: "Ian Munsick" },
{ title: "More Than Me", artist: "Ian Munsick" },
// Dillon James
{ title: "Something to Talk About", artist: "Dillon James" },
// ERNEST
{ title: "Flower Shops", artist: "ERNEST" },
{ title: "What It's Come To", artist: "ERNEST" },
// Jessie Murph
{ title: "Wild Ones", artist: "Jessie Murph" },
{ title: "Pray", artist: "Jessie Murph" },
// Josh Ross
{ title: "Single Again", artist: "Josh Ross" },
{ title: "First Taste of Gone", artist: "Josh Ross" },
// Warren Zeiders
{ title: "Ride the Lightning", artist: "Warren Zeiders" },
{ title: "Pretty Little Poison", artist: "Warren Zeiders" },
{ title: "Wild Horse", artist: "Warren Zeiders" },
{ title: "Dark Night", artist: "Warren Zeiders" },
// Corey Kent
{ title: "Wild as Her", artist: "Corey Kent" },
{ title: "Ain't My Day", artist: "Corey Kent" },
// Randall King
{ title: "Hey Cowgirl", artist: "Randall King" },
{ title: "Leanna", artist: "Randall King" },
// Kidd G
{ title: "Dirt Road", artist: "Kidd G" },
{ title: "Teenage Dream", artist: "Kidd G" },
// Jackson Dean
{ title: "Don't Come Lookin", artist: "Jackson Dean" },
{ title: "Fearless", artist: "Jackson Dean" },
// Megan Moroney
{ title: "Tennessee Orange", artist: "Megan Moroney" },
{ title: "No Caller ID", artist: "Megan Moroney" },
{ title: "I'm Not Pretty", artist: "Megan Moroney" },
{ title: "Indifferent", artist: "Megan Moroney" },
{ title: "Am I Okay", artist: "Megan Moroney" },
// Post Malone (country crossover)
{ title: "I Had Some Help", artist: "Post Malone" },
{ title: "Pour Me a Drink", artist: "Post Malone" },
{ title: "Yours", artist: "Post Malone" },
// Beyonce (country crossover)
{ title: "Texas Hold Em", artist: "Beyonce" },
{ title: "16 Carriages", artist: "Beyonce" },
// Shaboozey
{ title: "A Bar Song (Tipsy)", artist: "Shaboozey" },
{ title: "Let It Burn", artist: "Shaboozey" },
// Teddy Swims (country crossover)
{ title: "Lose Control", artist: "Teddy Swims" },
// Clay Walker
{ title: "Live Until I Die", artist: "Clay Walker" },
{ title: "What's It to You", artist: "Clay Walker" },
{ title: "Dreaming with My Eyes Open", artist: "Clay Walker" },
{ title: "If I Could Make a Living", artist: "Clay Walker" },
{ title: "This Woman and This Man", artist: "Clay Walker" },
// Mark Chesnutt
{ title: "Bubba Shot the Jukebox", artist: "Mark Chesnutt" },
{ title: "I Just Wanted You to Know", artist: "Mark Chesnutt" },
{ title: "Brother Jukebox", artist: "Mark Chesnutt" },
// Joe Nichols
{ title: "Brokenheartsville", artist: "Joe Nichols" },
{ title: "Tequila Makes Her Clothes Fall Off", artist: "Joe Nichols" },
{ title: "Gimme That Girl", artist: "Joe Nichols" },
{ title: "Sunny and 75", artist: "Joe Nichols" },
// David Allan Coe
{ title: "You Never Even Called Me by My Name", artist: "David Allan Coe" },
{ title: "The Ride", artist: "David Allan Coe" },
{ title: "Mona Lisa Lost Her Smile", artist: "David Allan Coe" },
// Lynyrd Skynyrd (country/southern rock crossover)
{ title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
{ title: "Free Bird", artist: "Lynyrd Skynyrd" },
{ title: "Simple Man", artist: "Lynyrd Skynyrd" },
// Charlie Daniels Band
{ title: "The Devil Went Down to Georgia", artist: "Charlie Daniels Band" },
{ title: "Long Haired Country Boy", artist: "Charlie Daniels Band" },
{ title: "Uneasy Rider", artist: "Charlie Daniels Band" },
// Nelly (country crossover)
{ title: "Over and Over", artist: "Nelly" },
// Caylee Hammack
{ title: "Family Tree", artist: "Caylee Hammack" },
{ title: "Small Town Hypocrite", artist: "Caylee Hammack" },
// Kassi Ashton
{ title: "Dates in Pickup Trucks", artist: "Kassi Ashton" },
// Dasha
{ title: "Austin", artist: "Dasha" },
{ title: "None of This Has Been About You", artist: "Dasha" },
// Elle King
{ title: "Drunk (And I Don't Wanna Go Home)", artist: "Elle King" },
// George Birge
{ title: "Beer Beer Truck Truck", artist: "George Birge" },
{ title: "Mind on You", artist: "George Birge" },
// Anne Wilson
{ title: "My Jesus", artist: "Anne Wilson" },
// Breland
{ title: "My Truck", artist: "Breland" },
{ title: "Cross Country", artist: "Breland" },
// Jess Carson (Midland solo)
{ title: "Girl Like You", artist: "Jason Aldean" },
// Stoney LaRue
{ title: "Feet Don't Touch the Ground", artist: "Stoney LaRue" },
{ title: "Down in Flames", artist: "Stoney LaRue" },
// Pat Green
{ title: "Wave on Wave", artist: "Pat Green" },
{ title: "Baby Doll", artist: "Pat Green" },
{ title: "Carry On", artist: "Pat Green" },
// Cross Canadian Ragweed
{ title: "17", artist: "Cross Canadian Ragweed" },
{ title: "Alabama", artist: "Cross Canadian Ragweed" },
// Robert Earl Keen
{ title: "The Road Goes on Forever", artist: "Robert Earl Keen" },
{ title: "Gringo Honeymoon", artist: "Robert Earl Keen" },
{ title: "Corpus Christi Bay", artist: "Robert Earl Keen" },
// Townes Van Zandt
{ title: "Pancho and Lefty", artist: "Townes Van Zandt" },
{ title: "To Live Is to Fly", artist: "Townes Van Zandt" },
{ title: "If I Needed You", artist: "Townes Van Zandt" },
// Blanco Brown
{ title: "The Git Up", artist: "Blanco Brown" },
// Jimmie Rodgers
{ title: "Blue Yodel", artist: "Jimmie Rodgers" },
{ title: "In the Jailhouse Now", artist: "Jimmie Rodgers" },
// Buck Owens
{ title: "Act Naturally", artist: "Buck Owens" },
{ title: "Love's Gonna Live Here", artist: "Buck Owens" },
{ title: "Together Again", artist: "Buck Owens" },
// Larry Fleet
{ title: "Where I Find God", artist: "Larry Fleet" },
{ title: "Where I Belong", artist: "Larry Fleet" },
// Dalton Dover
{ title: "Giving Up on That", artist: "Dalton Dover" },
// Drake White
{ title: "Livin the Dream", artist: "Drake White" },
// Drayton Farley
{ title: "A Hard Way to Go", artist: "Drayton Farley" },
// Wallen/Bryan collab
{ title: "Countryfied", artist: "Morgan Wallen" },
// Post Malone
{ title: "Guy for That", artist: "Post Malone" },
