// === POP (Part 1: Artists 1-40) ===

// --- Taylor Swift ---
  { title: "Cruel Summer", artist: "Taylor Swift" },
  { title: "Anti-Hero", artist: "Taylor Swift" },
  { title: "Shake It Off", artist: "Taylor Swift" },
  { title: "Blank Space", artist: "Taylor Swift" },
  { title: "Love Story", artist: "Taylor Swift" },
  { title: "You Belong with Me", artist: "Taylor Swift" },
  { title: "Style", artist: "Taylor Swift" },
  { title: "Delicate", artist: "Taylor Swift" },
  { title: "Cardigan", artist: "Taylor Swift" },
  { title: "Fortnight", artist: "Taylor Swift" },
  { title: "Lover", artist: "Taylor Swift" },
  { title: "Wildest Dreams", artist: "Taylor Swift" },
  { title: "22", artist: "Taylor Swift" },
  { title: "We Are Never Getting Back Together", artist: "Taylor Swift" },
  { title: "Bad Blood", artist: "Taylor Swift" },

// --- Ariana Grande ---
  { title: "thank u, next", artist: "Ariana Grande" },
  { title: "7 rings", artist: "Ariana Grande" },
  { title: "Positions", artist: "Ariana Grande" },
  { title: "no tears left to cry", artist: "Ariana Grande" },
  { title: "Into You", artist: "Ariana Grande" },
  { title: "Problem", artist: "Ariana Grande" },
  { title: "Side to Side", artist: "Ariana Grande" },
  { title: "Break Free", artist: "Ariana Grande" },
  { title: "One Last Time", artist: "Ariana Grande" },
  { title: "God Is a Woman", artist: "Ariana Grande" },
  { title: "Dangerous Woman", artist: "Ariana Grande" },
  { title: "Rain On Me", artist: "Ariana Grande" },
  { title: "Bang Bang", artist: "Ariana Grande" },
  { title: "Love Me Harder", artist: "Ariana Grande" },
  { title: "Stuck with U", artist: "Ariana Grande" },

// --- Ed Sheeran ---
  { title: "Shape of You", artist: "Ed Sheeran" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { title: "Photograph", artist: "Ed Sheeran" },
  { title: "Perfect", artist: "Ed Sheeran" },
  { title: "Castle on the Hill", artist: "Ed Sheeran" },
  { title: "Galway Girl", artist: "Ed Sheeran" },
  { title: "Bad Habits", artist: "Ed Sheeran" },
  { title: "Shivers", artist: "Ed Sheeran" },
  { title: "Happier", artist: "Ed Sheeran" },
  { title: "The A Team", artist: "Ed Sheeran" },
  { title: "Lego House", artist: "Ed Sheeran" },
  { title: "Sing", artist: "Ed Sheeran" },
  { title: "Don't", artist: "Ed Sheeran" },
  { title: "Drunk", artist: "Ed Sheeran" },
  { title: "Eyes Closed", artist: "Ed Sheeran" },

// --- Dua Lipa ---
  { title: "Levitating", artist: "Dua Lipa" },
  { title: "Don't Start Now", artist: "Dua Lipa" },
  { title: "New Rules", artist: "Dua Lipa" },
  { title: "Physical", artist: "Dua Lipa" },
  { title: "IDGAF", artist: "Dua Lipa" },
  { title: "One Kiss", artist: "Dua Lipa" },
  { title: "Break My Heart", artist: "Dua Lipa" },
  { title: "Houdini", artist: "Dua Lipa" },
  { title: "Training Season", artist: "Dua Lipa" },
  { title: "Cold Heart", artist: "Dua Lipa" },
  { title: "Love Again", artist: "Dua Lipa" },
  { title: "Electricity", artist: "Dua Lipa" },
  { title: "Scared to Be Lonely", artist: "Dua Lipa" },
  { title: "Be the One", artist: "Dua Lipa" },
  { title: "Blow Your Mind", artist: "Dua Lipa" },

// --- The Weeknd ---
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Save Your Tears", artist: "The Weeknd" },
  { title: "Starboy", artist: "The Weeknd" },
  { title: "The Hills", artist: "The Weeknd" },
  { title: "Can't Feel My Face", artist: "The Weeknd" },
  { title: "After Hours", artist: "The Weeknd" },
  { title: "Call Out My Name", artist: "The Weeknd" },
  { title: "Earned It", artist: "The Weeknd" },
  { title: "I Feel It Coming", artist: "The Weeknd" },
  { title: "Heartless", artist: "The Weeknd" },
  { title: "Die for You", artist: "The Weeknd" },
  { title: "Out of Time", artist: "The Weeknd" },
  { title: "In Your Eyes", artist: "The Weeknd" },
  { title: "Often", artist: "The Weeknd" },
  { title: "Sacrifice", artist: "The Weeknd" },

// --- Billie Eilish ---
  { title: "bad guy", artist: "Billie Eilish" },
  { title: "Happier Than Ever", artist: "Billie Eilish" },
  { title: "lovely", artist: "Billie Eilish" },
  { title: "everything i wanted", artist: "Billie Eilish" },
  { title: "when the party's over", artist: "Billie Eilish" },
  { title: "Therefore I Am", artist: "Billie Eilish" },
  { title: "ocean eyes", artist: "Billie Eilish" },
  { title: "bury a friend", artist: "Billie Eilish" },
  { title: "No Time to Die", artist: "Billie Eilish" },
  { title: "Birds of a Feather", artist: "Billie Eilish" },
  { title: "Lunch", artist: "Billie Eilish" },
  { title: "What Was I Made For", artist: "Billie Eilish" },
  { title: "idontwannabeyouanymore", artist: "Billie Eilish" },
  { title: "my future", artist: "Billie Eilish" },
  { title: "Lovely", artist: "Billie Eilish" },

// --- Harry Styles ---
  { title: "As It Was", artist: "Harry Styles" },
  { title: "Watermelon Sugar", artist: "Harry Styles" },
  { title: "Adore You", artist: "Harry Styles" },
  { title: "Sign of the Times", artist: "Harry Styles" },
  { title: "Late Night Talking", artist: "Harry Styles" },
  { title: "Golden", artist: "Harry Styles" },
  { title: "Falling", artist: "Harry Styles" },
  { title: "Kiwi", artist: "Harry Styles" },
  { title: "Matilda", artist: "Harry Styles" },
  { title: "Lights Up", artist: "Harry Styles" },
  { title: "Music for a Sushi Restaurant", artist: "Harry Styles" },
  { title: "Satellite", artist: "Harry Styles" },
  { title: "Daydreaming", artist: "Harry Styles" },
  { title: "Fine Line", artist: "Harry Styles" },
  { title: "Treat People with Kindness", artist: "Harry Styles" },

// --- Olivia Rodrigo ---
  { title: "drivers license", artist: "Olivia Rodrigo" },
  { title: "good 4 u", artist: "Olivia Rodrigo" },
  { title: "vampire", artist: "Olivia Rodrigo" },
  { title: "deja vu", artist: "Olivia Rodrigo" },
  { title: "traitor", artist: "Olivia Rodrigo" },
  { title: "brutal", artist: "Olivia Rodrigo" },
  { title: "happier", artist: "Olivia Rodrigo" },
  { title: "favorite crime", artist: "Olivia Rodrigo" },
  { title: "jealousy, jealousy", artist: "Olivia Rodrigo" },
  { title: "All-American Bitch", artist: "Olivia Rodrigo" },
  { title: "get him back!", artist: "Olivia Rodrigo" },
  { title: "bad idea right?", artist: "Olivia Rodrigo" },
  { title: "enough for you", artist: "Olivia Rodrigo" },
  { title: "1 step forward, 3 steps back", artist: "Olivia Rodrigo" },
  { title: "So American", artist: "Olivia Rodrigo" },

// --- Bruno Mars ---
  { title: "Uptown Funk", artist: "Bruno Mars" },
  { title: "Just the Way You Are", artist: "Bruno Mars" },
  { title: "Grenade", artist: "Bruno Mars" },
  { title: "When I Was Your Man", artist: "Bruno Mars" },
  { title: "That's What I Like", artist: "Bruno Mars" },
  { title: "24K Magic", artist: "Bruno Mars" },
  { title: "Locked Out of Heaven", artist: "Bruno Mars" },
  { title: "The Lazy Song", artist: "Bruno Mars" },
  { title: "Treasure", artist: "Bruno Mars" },
  { title: "Count on Me", artist: "Bruno Mars" },
  { title: "Marry You", artist: "Bruno Mars" },
  { title: "It Will Rain", artist: "Bruno Mars" },
  { title: "Finesse", artist: "Bruno Mars" },
  { title: "Talking to the Moon", artist: "Bruno Mars" },
  { title: "Leave the Door Open", artist: "Bruno Mars" },

// --- Justin Bieber ---
  { title: "Sorry", artist: "Justin Bieber" },
  { title: "Love Yourself", artist: "Justin Bieber" },
  { title: "Peaches", artist: "Justin Bieber" },
  { title: "What Do You Mean?", artist: "Justin Bieber" },
  { title: "Stay", artist: "Justin Bieber" },
  { title: "Baby", artist: "Justin Bieber" },
  { title: "Yummy", artist: "Justin Bieber" },
  { title: "Ghost", artist: "Justin Bieber" },
  { title: "Intentions", artist: "Justin Bieber" },
  { title: "Let Me Love You", artist: "Justin Bieber" },
  { title: "Cold Water", artist: "Justin Bieber" },
  { title: "Boyfriend", artist: "Justin Bieber" },
  { title: "As Long as You Love Me", artist: "Justin Bieber" },
  { title: "Beauty and a Beat", artist: "Justin Bieber" },
  { title: "Holy", artist: "Justin Bieber" },

// --- Rihanna ---
  { title: "Umbrella", artist: "Rihanna" },
  { title: "We Found Love", artist: "Rihanna" },
  { title: "Diamonds", artist: "Rihanna" },
  { title: "Stay", artist: "Rihanna" },
  { title: "Work", artist: "Rihanna" },
  { title: "Don't Stop the Music", artist: "Rihanna" },
  { title: "Only Girl (In the World)", artist: "Rihanna" },
  { title: "Rude Boy", artist: "Rihanna" },
  { title: "S.O.S.", artist: "Rihanna" },
  { title: "Disturbia", artist: "Rihanna" },
  { title: "What's My Name?", artist: "Rihanna" },
  { title: "Needed Me", artist: "Rihanna" },
  { title: "Love on the Brain", artist: "Rihanna" },
  { title: "Lift Me Up", artist: "Rihanna" },
  { title: "Pour It Up", artist: "Rihanna" },

// --- Lady Gaga ---
  { title: "Shallow", artist: "Lady Gaga" },
  { title: "Bad Romance", artist: "Lady Gaga" },
  { title: "Poker Face", artist: "Lady Gaga" },
  { title: "Just Dance", artist: "Lady Gaga" },
  { title: "Born This Way", artist: "Lady Gaga" },
  { title: "Rain On Me", artist: "Lady Gaga" },
  { title: "Alejandro", artist: "Lady Gaga" },
  { title: "The Edge of Glory", artist: "Lady Gaga" },
  { title: "Telephone", artist: "Lady Gaga" },
  { title: "Paparazzi", artist: "Lady Gaga" },
  { title: "Applause", artist: "Lady Gaga" },
  { title: "Million Reasons", artist: "Lady Gaga" },
  { title: "Stupid Love", artist: "Lady Gaga" },
  { title: "Always Remember Us This Way", artist: "Lady Gaga" },
  { title: "Die With a Smile", artist: "Lady Gaga" },

// --- Katy Perry ---
  { title: "Roar", artist: "Katy Perry" },
  { title: "Firework", artist: "Katy Perry" },
  { title: "Dark Horse", artist: "Katy Perry" },
  { title: "Teenage Dream", artist: "Katy Perry" },
  { title: "California Gurls", artist: "Katy Perry" },
  { title: "Last Friday Night", artist: "Katy Perry" },
  { title: "Hot N Cold", artist: "Katy Perry" },
  { title: "I Kissed a Girl", artist: "Katy Perry" },
  { title: "Wide Awake", artist: "Katy Perry" },
  { title: "Part of Me", artist: "Katy Perry" },
  { title: "The One That Got Away", artist: "Katy Perry" },
  { title: "E.T.", artist: "Katy Perry" },
  { title: "Chained to the Rhythm", artist: "Katy Perry" },
  { title: "Bon Appetit", artist: "Katy Perry" },
  { title: "Never Really Over", artist: "Katy Perry" },

// --- Beyonce ---
  { title: "Crazy in Love", artist: "Beyonce" },
  { title: "Halo", artist: "Beyonce" },
  { title: "Single Ladies", artist: "Beyonce" },
  { title: "Irreplaceable", artist: "Beyonce" },
  { title: "Drunk in Love", artist: "Beyonce" },
  { title: "Formation", artist: "Beyonce" },
  { title: "Love on Top", artist: "Beyonce" },
  { title: "If I Were a Boy", artist: "Beyonce" },
  { title: "Run the World (Girls)", artist: "Beyonce" },
  { title: "XO", artist: "Beyonce" },
  { title: "Lemonade", artist: "Beyonce" },
  { title: "Break My Soul", artist: "Beyonce" },
  { title: "CUFF IT", artist: "Beyonce" },
  { title: "TEXAS HOLD 'EM", artist: "Beyonce" },
  { title: "16 CARRIAGES", artist: "Beyonce" },

// --- Adele ---
  { title: "Rolling in the Deep", artist: "Adele" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Hello", artist: "Adele" },
  { title: "Set Fire to the Rain", artist: "Adele" },
  { title: "Easy On Me", artist: "Adele" },
  { title: "Skyfall", artist: "Adele" },
  { title: "When We Were Young", artist: "Adele" },
  { title: "Chasing Pavements", artist: "Adele" },
  { title: "Make You Feel My Love", artist: "Adele" },
  { title: "Send My Love", artist: "Adele" },
  { title: "Water Under the Bridge", artist: "Adele" },
  { title: "Rumour Has It", artist: "Adele" },
  { title: "Turning Tables", artist: "Adele" },
  { title: "Oh My God", artist: "Adele" },
  { title: "All I Ask", artist: "Adele" },

// --- Sia ---
  { title: "Cheap Thrills", artist: "Sia" },
  { title: "Chandelier", artist: "Sia" },
  { title: "Elastic Heart", artist: "Sia" },
  { title: "Titanium", artist: "Sia" },
  { title: "Unstoppable", artist: "Sia" },
  { title: "Alive", artist: "Sia" },
  { title: "The Greatest", artist: "Sia" },
  { title: "Breathe Me", artist: "Sia" },
  { title: "Move Your Body", artist: "Sia" },
  { title: "Bird Set Free", artist: "Sia" },
  { title: "Fire Meet Gasoline", artist: "Sia" },
  { title: "Big Girls Cry", artist: "Sia" },
  { title: "Never Give Up", artist: "Sia" },
  { title: "Together", artist: "Sia" },
  { title: "Courage to Change", artist: "Sia" },

// --- Miley Cyrus ---
  { title: "Flowers", artist: "Miley Cyrus" },
  { title: "Wrecking Ball", artist: "Miley Cyrus" },
  { title: "Party in the U.S.A.", artist: "Miley Cyrus" },
  { title: "We Can't Stop", artist: "Miley Cyrus" },
  { title: "The Climb", artist: "Miley Cyrus" },
  { title: "Midnight Sky", artist: "Miley Cyrus" },
  { title: "Malibu", artist: "Miley Cyrus" },
  { title: "Adore You", artist: "Miley Cyrus" },
  { title: "See You Again", artist: "Miley Cyrus" },
  { title: "7 Things", artist: "Miley Cyrus" },
  { title: "Prisoner", artist: "Miley Cyrus" },
  { title: "Nothing Breaks Like a Heart", artist: "Miley Cyrus" },
  { title: "Mother's Daughter", artist: "Miley Cyrus" },
  { title: "Used to Be Young", artist: "Miley Cyrus" },
  { title: "River", artist: "Miley Cyrus" },

// --- Shawn Mendes ---
  { title: "Stitches", artist: "Shawn Mendes" },
  { title: "Treat You Better", artist: "Shawn Mendes" },
  { title: "There's Nothing Holdin' Me Back", artist: "Shawn Mendes" },
  { title: "In My Blood", artist: "Shawn Mendes" },
  { title: "Senorita", artist: "Shawn Mendes" },
  { title: "Mercy", artist: "Shawn Mendes" },
  { title: "If I Can't Have You", artist: "Shawn Mendes" },
  { title: "Wonder", artist: "Shawn Mendes" },
  { title: "Lost in Japan", artist: "Shawn Mendes" },
  { title: "Nervous", artist: "Shawn Mendes" },
  { title: "Life of the Party", artist: "Shawn Mendes" },
  { title: "Perfectly Wrong", artist: "Shawn Mendes" },
  { title: "It'll Be Okay", artist: "Shawn Mendes" },
  { title: "When You're Gone", artist: "Shawn Mendes" },
  { title: "Youth", artist: "Shawn Mendes" },

// --- Camila Cabello ---
  { title: "Havana", artist: "Camila Cabello" },
  { title: "Senorita", artist: "Camila Cabello" },
  { title: "Never Be the Same", artist: "Camila Cabello" },
  { title: "Bam Bam", artist: "Camila Cabello" },
  { title: "My Oh My", artist: "Camila Cabello" },
  { title: "Crying in the Club", artist: "Camila Cabello" },
  { title: "Liar", artist: "Camila Cabello" },
  { title: "Shameless", artist: "Camila Cabello" },
  { title: "Don't Go Yet", artist: "Camila Cabello" },
  { title: "Real Friends", artist: "Camila Cabello" },

// --- Halsey ---
  { title: "Without Me", artist: "Halsey" },
  { title: "Bad at Love", artist: "Halsey" },
  { title: "Closer", artist: "Halsey" },
  { title: "Graveyard", artist: "Halsey" },
  { title: "You should be sad", artist: "Halsey" },
  { title: "Colors", artist: "Halsey" },
  { title: "Now or Never", artist: "Halsey" },
  { title: "Eastside", artist: "Halsey" },
  { title: "Nightmare", artist: "Halsey" },
  { title: "Castle", artist: "Halsey" },
  { title: "New Americana", artist: "Halsey" },
  { title: "Gasoline", artist: "Halsey" },
  { title: "Ghost", artist: "Halsey" },
  { title: "I am not a woman, I'm a god", artist: "Halsey" },
  { title: "So Good", artist: "Halsey" },

// --- Doja Cat ---
  { title: "Say So", artist: "Doja Cat" },
  { title: "Kiss Me More", artist: "Doja Cat" },
  { title: "Need to Know", artist: "Doja Cat" },
  { title: "Woman", artist: "Doja Cat" },
  { title: "Streets", artist: "Doja Cat" },
  { title: "Paint the Town Red", artist: "Doja Cat" },
  { title: "Agora Hills", artist: "Doja Cat" },
  { title: "Get Into It (Yuh)", artist: "Doja Cat" },
  { title: "Mooo!", artist: "Doja Cat" },
  { title: "Boss Bitch", artist: "Doja Cat" },
  { title: "You Right", artist: "Doja Cat" },
  { title: "Like That", artist: "Doja Cat" },
  { title: "Juicy", artist: "Doja Cat" },
  { title: "Attention", artist: "Doja Cat" },
  { title: "Vegas", artist: "Doja Cat" },

// --- Lizzo ---
  { title: "About Damn Time", artist: "Lizzo" },
  { title: "Truth Hurts", artist: "Lizzo" },
  { title: "Good as Hell", artist: "Lizzo" },
  { title: "Juice", artist: "Lizzo" },
  { title: "Tempo", artist: "Lizzo" },
  { title: "Cuz I Love You", artist: "Lizzo" },
  { title: "Boys", artist: "Lizzo" },
  { title: "Phone", artist: "Lizzo" },
  { title: "Rumors", artist: "Lizzo" },
  { title: "2 Be Loved", artist: "Lizzo" },

// --- Post Malone ---
  { title: "Circles", artist: "Post Malone" },
  { title: "Sunflower", artist: "Post Malone" },
  { title: "Rockstar", artist: "Post Malone" },
  { title: "Congratulations", artist: "Post Malone" },
  { title: "White Iverson", artist: "Post Malone" },
  { title: "Better Now", artist: "Post Malone" },
  { title: "Psycho", artist: "Post Malone" },
  { title: "I Like You", artist: "Post Malone" },
  { title: "Goodbyes", artist: "Post Malone" },
  { title: "Wow.", artist: "Post Malone" },
  { title: "Chemical", artist: "Post Malone" },
  { title: "Mourning", artist: "Post Malone" },
  { title: "I Had Some Help", artist: "Post Malone" },
  { title: "Cooped Up", artist: "Post Malone" },
  { title: "One Right Now", artist: "Post Malone" },

// --- Maroon 5 ---
  { title: "Sugar", artist: "Maroon 5" },
  { title: "Moves Like Jagger", artist: "Maroon 5" },
  { title: "Girls Like You", artist: "Maroon 5" },
  { title: "Payphone", artist: "Maroon 5" },
  { title: "Maps", artist: "Maroon 5" },
  { title: "She Will Be Loved", artist: "Maroon 5" },
  { title: "This Love", artist: "Maroon 5" },
  { title: "Sunday Morning", artist: "Maroon 5" },
  { title: "Memories", artist: "Maroon 5" },
  { title: "Animals", artist: "Maroon 5" },
  { title: "One More Night", artist: "Maroon 5" },
  { title: "Harder to Breathe", artist: "Maroon 5" },
  { title: "Love Somebody", artist: "Maroon 5" },
  { title: "Wait", artist: "Maroon 5" },
  { title: "Beautiful Mistakes", artist: "Maroon 5" },

// --- OneRepublic ---
  { title: "Counting Stars", artist: "OneRepublic" },
  { title: "Apologize", artist: "OneRepublic" },
  { title: "Stop and Stare", artist: "OneRepublic" },
  { title: "Secrets", artist: "OneRepublic" },
  { title: "Good Life", artist: "OneRepublic" },
  { title: "If I Lose Myself", artist: "OneRepublic" },
  { title: "Love Runs Out", artist: "OneRepublic" },
  { title: "Wherever I Go", artist: "OneRepublic" },
  { title: "I Lived", artist: "OneRepublic" },
  { title: "Something I Need", artist: "OneRepublic" },
  { title: "Rescue Me", artist: "OneRepublic" },
  { title: "Run", artist: "OneRepublic" },
  { title: "I Ain't Worried", artist: "OneRepublic" },
  { title: "Somebody to Love", artist: "OneRepublic" },
  { title: "Marchin On", artist: "OneRepublic" },

// --- Imagine Dragons ---
  { title: "Radioactive", artist: "Imagine Dragons" },
  { title: "Believer", artist: "Imagine Dragons" },
  { title: "Demons", artist: "Imagine Dragons" },
  { title: "Thunder", artist: "Imagine Dragons" },
  { title: "Whatever It Takes", artist: "Imagine Dragons" },
  { title: "It's Time", artist: "Imagine Dragons" },
  { title: "Natural", artist: "Imagine Dragons" },
  { title: "On Top of the World", artist: "Imagine Dragons" },
  { title: "Bones", artist: "Imagine Dragons" },
  { title: "Enemy", artist: "Imagine Dragons" },
  { title: "Bad Liar", artist: "Imagine Dragons" },
  { title: "Walking the Wire", artist: "Imagine Dragons" },
  { title: "Amsterdam", artist: "Imagine Dragons" },
  { title: "Shots", artist: "Imagine Dragons" },
  { title: "Eyes Closed", artist: "Imagine Dragons" },

// --- Selena Gomez ---
  { title: "Lose You to Love Me", artist: "Selena Gomez" },
  { title: "Come & Get It", artist: "Selena Gomez" },
  { title: "Good for You", artist: "Selena Gomez" },
  { title: "Same Old Love", artist: "Selena Gomez" },
  { title: "Hands to Myself", artist: "Selena Gomez" },
  { title: "Back to You", artist: "Selena Gomez" },
  { title: "Wolves", artist: "Selena Gomez" },
  { title: "Bad Liar", artist: "Selena Gomez" },
  { title: "Fetish", artist: "Selena Gomez" },
  { title: "Rare", artist: "Selena Gomez" },
  { title: "Look at Her Now", artist: "Selena Gomez" },
  { title: "It Ain't Me", artist: "Selena Gomez" },
  { title: "Love You Like a Love Song", artist: "Selena Gomez" },
  { title: "Single Soon", artist: "Selena Gomez" },
  { title: "My Mind & Me", artist: "Selena Gomez" },

// --- P!nk ---
  { title: "Raise Your Glass", artist: "P!nk" },
  { title: "So What", artist: "P!nk" },
  { title: "Just Give Me a Reason", artist: "P!nk" },
  { title: "Try", artist: "P!nk" },
  { title: "What About Us", artist: "P!nk" },
  { title: "Get the Party Started", artist: "P!nk" },
  { title: "Just Like a Pill", artist: "P!nk" },
  { title: "Who Knew", artist: "P!nk" },
  { title: "Blow Me (One Last Kiss)", artist: "P!nk" },
  { title: "Trouble", artist: "P!nk" },
  { title: "Don't Let Me Get Me", artist: "P!nk" },
  { title: "Beautiful Trauma", artist: "P!nk" },
  { title: "Cover Me in Sunshine", artist: "P!nk" },
  { title: "Walk Me Home", artist: "P!nk" },
  { title: "TRUSTFALL", artist: "P!nk" },

// --- Shakira ---
  { title: "Hips Don't Lie", artist: "Shakira" },
  { title: "Whenever, Wherever", artist: "Shakira" },
  { title: "Waka Waka", artist: "Shakira" },
  { title: "She Wolf", artist: "Shakira" },
  { title: "Chantaje", artist: "Shakira" },
  { title: "La Tortura", artist: "Shakira" },
  { title: "Loca", artist: "Shakira" },
  { title: "Underneath Your Clothes", artist: "Shakira" },
  { title: "Beautiful Liar", artist: "Shakira" },
  { title: "Try Everything", artist: "Shakira" },
  { title: "Can't Remember to Forget You", artist: "Shakira" },
  { title: "Rabiosa", artist: "Shakira" },
  { title: "Bzrp Music Sessions, Vol. 53", artist: "Shakira" },
  { title: "Girl Like Me", artist: "Shakira" },
  { title: "Objection", artist: "Shakira" },

// --- Sam Smith ---
  { title: "Stay With Me", artist: "Sam Smith" },
  { title: "Too Good at Goodbyes", artist: "Sam Smith" },
  { title: "I'm Not the Only One", artist: "Sam Smith" },
  { title: "Writing's on the Wall", artist: "Sam Smith" },
  { title: "Lay Me Down", artist: "Sam Smith" },
  { title: "Like I Can", artist: "Sam Smith" },
  { title: "Dancing with a Stranger", artist: "Sam Smith" },
  { title: "How Do You Sleep?", artist: "Sam Smith" },
  { title: "Promises", artist: "Sam Smith" },
  { title: "Unholy", artist: "Sam Smith" },
  { title: "Latch", artist: "Sam Smith" },
  { title: "Money on My Mind", artist: "Sam Smith" },
  { title: "Fire on Fire", artist: "Sam Smith" },
  { title: "Diamonds", artist: "Sam Smith" },
  { title: "I Feel Love", artist: "Sam Smith" },

// --- Lorde ---
  { title: "Royals", artist: "Lorde" },
  { title: "Team", artist: "Lorde" },
  { title: "Green Light", artist: "Lorde" },
  { title: "Ribs", artist: "Lorde" },
  { title: "Buzzcut Season", artist: "Lorde" },
  { title: "Liability", artist: "Lorde" },
  { title: "Perfect Places", artist: "Lorde" },
  { title: "Tennis Court", artist: "Lorde" },
  { title: "Homemade Dynamite", artist: "Lorde" },
  { title: "Solar Power", artist: "Lorde" },
  { title: "Supercut", artist: "Lorde" },
  { title: "The Louvre", artist: "Lorde" },
  { title: "Hard Feelings", artist: "Lorde" },
  { title: "A World Alone", artist: "Lorde" },
  { title: "Writer in the Dark", artist: "Lorde" },

// --- Charli XCX ---
  { title: "Boom Clap", artist: "Charli XCX" },
  { title: "Speed Drive", artist: "Charli XCX" },
  { title: "360", artist: "Charli XCX" },
  { title: "Apple", artist: "Charli XCX" },
  { title: "Von dutch", artist: "Charli XCX" },
  { title: "Sympathy is a knife", artist: "Charli XCX" },
  { title: "I Love It", artist: "Charli XCX" },
  { title: "1999", artist: "Charli XCX" },
  { title: "Boys", artist: "Charli XCX" },
  { title: "Good Ones", artist: "Charli XCX" },
  { title: "Used to Know Me", artist: "Charli XCX" },
  { title: "Vroom Vroom", artist: "Charli XCX" },
  { title: "Gone", artist: "Charli XCX" },
  { title: "Doing It", artist: "Charli XCX" },
  { title: "Break the Rules", artist: "Charli XCX" },

// --- Sabrina Carpenter ---
  { title: "Espresso", artist: "Sabrina Carpenter" },
  { title: "Please Please Please", artist: "Sabrina Carpenter" },
  { title: "Nonsense", artist: "Sabrina Carpenter" },
  { title: "Feather", artist: "Sabrina Carpenter" },
  { title: "Taste", artist: "Sabrina Carpenter" },
  { title: "Skinny Dipping", artist: "Sabrina Carpenter" },
  { title: "because i liked a boy", artist: "Sabrina Carpenter" },
  { title: "Fast Times", artist: "Sabrina Carpenter" },
  { title: "Bed Chem", artist: "Sabrina Carpenter" },
  { title: "Slim Pickins", artist: "Sabrina Carpenter" },
  { title: "Thumbs", artist: "Sabrina Carpenter" },
  { title: "Vicious", artist: "Sabrina Carpenter" },
  { title: "Sue Me", artist: "Sabrina Carpenter" },
  { title: "On Purpose", artist: "Sabrina Carpenter" },
  { title: "Lie to Girls", artist: "Sabrina Carpenter" },

// --- Chappell Roan ---
  { title: "Good Luck, Babe!", artist: "Chappell Roan" },
  { title: "Hot to Go!", artist: "Chappell Roan" },
  { title: "Red Wine Supernova", artist: "Chappell Roan" },
  { title: "Pink Pony Club", artist: "Chappell Roan" },
  { title: "Femininomenon", artist: "Chappell Roan" },
  { title: "Casual", artist: "Chappell Roan" },
  { title: "My Kink Is Karma", artist: "Chappell Roan" },
  { title: "After Midnight", artist: "Chappell Roan" },
  { title: "Coffee", artist: "Chappell Roan" },
  { title: "Super Graphic Ultra Modern Girl", artist: "Chappell Roan" },
  { title: "Naked in Manhattan", artist: "Chappell Roan" },
  { title: "California", artist: "Chappell Roan" },

// --- Charlie Puth ---
  { title: "Attention", artist: "Charlie Puth" },
  { title: "We Don't Talk Anymore", artist: "Charlie Puth" },
  { title: "See You Again", artist: "Charlie Puth" },
  { title: "One Call Away", artist: "Charlie Puth" },
  { title: "How Long", artist: "Charlie Puth" },
  { title: "Marvin Gaye", artist: "Charlie Puth" },
  { title: "Done for Me", artist: "Charlie Puth" },
  { title: "Light Switch", artist: "Charlie Puth" },
  { title: "That's Hilarious", artist: "Charlie Puth" },
  { title: "Left and Right", artist: "Charlie Puth" },

// --- Lewis Capaldi ---
  { title: "Someone You Loved", artist: "Lewis Capaldi" },
  { title: "Before You Go", artist: "Lewis Capaldi" },
  { title: "Bruises", artist: "Lewis Capaldi" },
  { title: "Hold Me While You Wait", artist: "Lewis Capaldi" },
  { title: "Forget Me", artist: "Lewis Capaldi" },
  { title: "Wish You the Best", artist: "Lewis Capaldi" },
  { title: "Grace", artist: "Lewis Capaldi" },
  { title: "Pointless", artist: "Lewis Capaldi" },
