// === ALL (50 biggest cross-genre hits 2000-2025) ===
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Shape of You", artist: "Ed Sheeran" },
  { title: "Uptown Funk", artist: "Bruno Mars" },
  { title: "Rolling in the Deep", artist: "Adele" },
  { title: "Bohemian Rhapsody", artist: "Queen" },
  { title: "Old Town Road", artist: "Lil Nas X" },
  { title: "Despacito", artist: "Luis Fonsi" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Happy", artist: "Pharrell Williams" },
  { title: "Closer", artist: "The Chainsmokers" },
  { title: "Levitating", artist: "Dua Lipa" },
  { title: "Bad Guy", artist: "Billie Eilish" },
  { title: "Lose Yourself", artist: "Eminem" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { title: "Cruel Summer", artist: "Taylor Swift" },
  { title: "As It Was", artist: "Harry Styles" },
  { title: "Anti-Hero", artist: "Taylor Swift" },
  { title: "Flowers", artist: "Miley Cyrus" },
  { title: "drivers license", artist: "Olivia Rodrigo" },
  { title: "Heat Waves", artist: "Glass Animals" },
  { title: "Shallow", artist: "Lady Gaga" },
  { title: "Dance Monkey", artist: "Tones and I" },
  { title: "Dynamite", artist: "BTS" },
  { title: "Save Your Tears", artist: "The Weeknd" },
  { title: "Don't Start Now", artist: "Dua Lipa" },
  { title: "Gods Plan", artist: "Drake" },
  { title: "Sicko Mode", artist: "Travis Scott" },
  { title: "HUMBLE.", artist: "Kendrick Lamar" },
  { title: "Stronger", artist: "Kanye West" },
  { title: "Mr. Brightside", artist: "The Killers" },
  { title: "Seven Nation Army", artist: "The White Stripes" },
  { title: "Viva la Vida", artist: "Coldplay" },
  { title: "In the End", artist: "Linkin Park" },
  { title: "Radioactive", artist: "Imagine Dragons" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { title: "Get Lucky", artist: "Daft Punk" },
  { title: "Hips Don't Lie", artist: "Shakira" },
  { title: "Crazy in Love", artist: "Beyonce" },
  { title: "Espresso", artist: "Sabrina Carpenter" },
  { title: "Sunflower", artist: "Post Malone" },
  { title: "Circles", artist: "Post Malone" },
  { title: "Stay", artist: "The Kid LAROI" },
  { title: "thank u, next", artist: "Ariana Grande" },
  { title: "Good 4 U", artist: "Olivia Rodrigo" },
  { title: "Havana", artist: "Camila Cabello" },
  { title: "Attention", artist: "Charlie Puth" },
  { title: "Someone You Loved", artist: "Lewis Capaldi" },
  { title: "Not Like Us", artist: "Kendrick Lamar" },
  { title: "Watermelon Sugar", artist: "Harry Styles" },
